### ISSUE TITLE
Linux version?

### ISSUE THREAD

**Issue by m1guelpf** [headsetapp/headset-electron#1]
Is there a Linux version available?

**Comment by m1guelpf** [comment]
Used this command to create a linux version:
``` bash
electron-packager . --ignore=node_modules/electron-prebuilt --ignore=node_modules/electron-packager --out build/ --overwrite --icon=Icon.png
```

**Comment by danielravina** [comment]
Hey that's awesome! I will add that to the build script. Funny how you can always expect Linux users to build their software themselves ;)

**Comment by m1guelpf** [comment]
@danielravina Maybe you could add build instructions to the README... (for all platforms)

**Comment by danielravina** [comment]
Thanks for mentioning that. I will do that once the Windows version is ready to go. There are some discrepancies between the systems so it takes a little longer. How is it working for you on Linux? which distro are you using? did you notice anything unusual?

**Comment by m1guelpf** [comment]
@danielravina I am using Ubuntu 16.10.
I have given it a lot of uses, and everything works smoothly, I love it!

**Comment by m1guelpf** [comment]
@danielravina Why don't you also release a linux version with the windows and mac ones?

**Comment by danielravina** [comment]
@m1guelpf were you able to get the Icon working on Ubuntu? I've been fighting this for two days now

**Comment by m1guelpf** [comment]
@danielravina Well, I did that manually. I added a .desktop file in /usr/share/applications to get it to show in the dock.

**Comment by m1guelpf** [comment]
@danielravina Cool, thank you!
