### ISSUE TITLE
Control volume of the app from the keyboard special buttons

### ISSUE THREAD

**Issue by mariusbancos** [headsetapp/headset-electron#109]
### Description

Control volume of the app from the keyboard special buttons

### Expected behaviour

I want to control the volume of the music played through the Headset app using the keyboard volume buttons.

### Actual behaviour

This doesn't happen as expected. For example the start/stop/back/forward buttons from the keyboard are working as expected but not the volume buttons.

### Your Environment

Ubuntu 16.04.1
Headset version:
Core: 1.3.9, Wrapper: v1.6.4

**Comment by m1guelpf** [comment]
@mariusbancos I think (@danielravina, correct me if I'm wrong) that's because Headset volume differs from your main volume. It's like the volume slider in YouTube videos, and I don't think we can map that to media keys.

**Comment by fcastilloec** [comment]
Like @m1guelpf said, this is not possible. The volume of Headset is separate (but still related) to the main volume.
You can control the volume of Headset using `dbus` and you can map that command to a shortcut. Headset uses `MPRIS` so it's easy to send a command to change the volume or control any other aspects of Headset.
You could also use [playerctl](https://github.com/acrisci/playerctl) which is a command line utility to control `MPRIS` players and map that to a shortcut.
Just know that if you change the volume through `MPRIS`, you'll find issue #78

**Comment by danielravina** [comment]
Technically it's possible to send keyboard volume events to the core app, and it will then respond with `volumeChange` event which will update the embedded youtube player. 
but, as @fcastilloec said, we are already utilizing MPRIS which is good enough and you can customize it to your needs.
