### ISSUE TITLE
Broken App Icon

### ISSUE THREAD

**Issue by ziyaddin** [headsetapp/headset-electron#11]
After app installation, app icon is set to Electron's default icon instead of Headset's.

![image](https://cloud.githubusercontent.com/assets/1016523/26117429/99d0df98-3a77-11e7-924a-0a7dadddc7f8.png)

Possible solution can be:
- providing manual .desktop entry for application

OR

- setting proper icon during installation

**Comment by danielravina** [comment]
This is a known issue with electron-packager in linux. https://github.com/headsetapp/headset-electron/issues/1 has the details. @m1guelpf are you able to share the `.desktop` file you created? I'll add it to the readme. Thanks

**Comment by m1guelpf** [comment]
My `.desktop` file:
```
#!/usr/bin/env xdg-open
[Desktop Entry]
Version=1.0
Type=Application
Terminal=false
Exec=/usr/share/headset/headset
Name=Headset
Icon=/usr/share/headset/resources/app/Icon.png
```
You need to point the icon & the exec to the extracted folder. @danielravina Where is the .deb extracted to?

**Comment by danielravina** [comment]
Thanks @m1guelpf! the .deb is extracted to `usr/lib/Headset`

**Comment by danielravina** [comment]
I update the readme with instructions. Thanks for reporting and thanks @m1guelpf for providing the .desktop file

**Comment by ziyaddin** [comment]
Thanks @danielravina and @m1guelpf
