### ISSUE TITLE
Collection overwritten

### ISSUE THREAD

**Issue by reddo** [headsetapp/headset-electron#110]
I use Headset both on Windows and Mac. My collection got overwritten when I've added some songs on the Mac (the collection was created in Windows, if that helps). I'm logged in on both platforms.

**Comment by danielravina** [comment]
Are you using both simultaneously? The synching mechanism will always override, there is no merging in the db and the backend doesn't send updates the client based on changes. It's not designed to work that way. In order to keep it in sync, you'll need to restart the windows app

**Comment by reddo** [comment]
No, not simultaneously, the windows app was not running while the mac one was and viceversa, the pc wasn't even on.

**Comment by danielravina** [comment]
hmm ok that's weird then. can you send the login email to hello@headsetapp.co and I'll investigate further? thanks.

**Comment by reddo** [comment]
I've added songs to that collection since. Is that a problem?

**Comment by danielravina** [comment]
shouldn't be a problem.

**Comment by reddo** [comment]
Looks like it's working fine now or it was a one-off issue. Thanks for the help and for following up with me!
