### ISSUE TITLE
Minimize to Tray

### ISSUE THREAD

**Issue by danielravina** [headsetapp/headset-electron#111]
### Description

Allow launching and minimizing Headset from the tray icon. It is possible to do via https://github.com/electron/electron/blob/master/docs/api/tray.md

**Comment by fcastilloec** [comment]
This shouldn't be implemented for Linux, the system tray has been phased out, so no minimizing to tray anymore.

**Comment by axydavid** [comment]
+1 for this.
Maybe not relevant for certain linux distros/mac.
But this would be a very welcomed feature in windows.

**Comment by fcastilloec** [comment]
This is available in `v1.9.0`
