### ISSUE TITLE
Add Options to disable notifications

### ISSUE THREAD

**Issue by danielravina** [headsetapp/headset-electron#118]
### Description
Some users really don't like the notifications popping up when tracks are playing. It's better to add a setting item under user profile with a toggle to disable them. There are ways to disable them via the OS, but it's not the best user experience.

### Workarounds
On windows:
![dtee6cnumaaiqwd jpg-large](https://user-images.githubusercontent.com/3150871/35822012-b10d5fe8-0a5f-11e8-9a8d-61046306152e.jpg)

On Mac:
<img width="780" alt="screen shot 2018-02-05 at 10 30 15 am" src="https://user-images.githubusercontent.com/3150871/35822018-b56d4472-0a5f-11e8-8c82-9d8175fca1d7.png">

On Linux:
No workaround

**Comment by fcastilloec** [comment]
On Linux, notifications are controlled by the app. So there's no way to disable them unless is implemented in Headset itself

**Comment by danielravina** [comment]
Thanks. updated the description

**Comment by danielravina** [comment]
Feature added in Core 1.8.3 🎉
