### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by mibofra** [headsetapp/headset-electron#12]
There should be a license with the project, like a gplv3+ for example.

**Comment by m1guelpf** [comment]
@mibofra Well, as the app itself is closed source, I believe there's no need for that...

**Comment by danielravina** [comment]
@mibofra you are right. I should add a license. Just need to pick one. @m1guelpf people can still contribute to this repo if they want.

**Comment by danielravina** [comment]
Added MIT (short and simple). Thanks!
