### ISSUE TITLE
Potentially adding headset to Chocolatey

### ISSUE THREAD

**Issue by PixelyIon** [headsetapp/headset-electron#124]
I was wondering if you guys could potentially add headset to Chocolatey(https://chocolatey.org/) so it'd be convienient to install for Windows users aswell..
Incase you don't know about Chocolatey it's basically a open-source package manager for windows so pretty similar to something like aptitude but for windows..

**Comment by danielravina** [comment]
I wouldn't mind adding that to chocolatey! Just don't have much time at the moment. If you want to open a PR and add it to the travis ci script, let me know! I'll sign up and provide the api key

**Comment by PixelyIon** [comment]
I'll look into it then ;)

**Comment by PixelyIon** [comment]
A small update I've looked into creating a package for chocolatey and most likely will be able to make one and integrate it into appveyor although it might take quite a bit of time as I'm busy studying for my exams..

**Comment by danielravina** [comment]
The app is on Chocolaty! https://chocolatey.org/packages/headset Thanks @fcastilloec for making this happen and @PixelyIon for making the suggestion!
