### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by curtisy1** [headsetapp/headset-electron#129]
### Description

The installation fails on my Windows 10 machine. I'm guessing it has something to do with already having a file with Releases in ./Githubdesktop?

I can still play music afterwards though, even when ignoring the error

### Expected behaviour

The installation should run through smoothly

### Actual behaviour

See description

### Your Environment

- Windows 10
- v1.7.0 ( pasting from user page is not possible unfortunately)

### Log
[SquirrelSetup.log](https://github.com/headsetapp/headset-electron/files/1799880/SquirrelSetup.log)

**Comment by danielravina** [comment]
did you modify your os datetime? the dates in the log are all over the place 
2017-08-13 - 2018-03-11

**Comment by fcastilloec** [comment]
I can replicate this on Windows 7 and 8. I'll try to debug it this weekend and see what I can come up with

**Comment by curtisy1** [comment]
Yeah, that's probably a squirrel related issue, because it fails to write to Release in my case (I think?). OS date is correct though.

I'll also poke around a little more and see if I can find a fix myself.

Thanks for the quick answers by the way! Appreciate it

**Comment by danielravina** [comment]
I got this window right before the error message. did you see something similar?
<img width="1440" alt="screen shot 2018-03-10 at 3 35 29 pm" src="https://user-images.githubusercontent.com/3150871/37247921-c743d700-2478-11e8-9be6-f5b25430cd61.png">

**Comment by fcastilloec** [comment]
I get the same thing, "Update has stopped working"

**Comment by danielravina** [comment]
I tried [v1.6.4](https://github.com/headsetapp/headset-electron/releases/tag/v1.6.4) and I don't see this error so it must be a problem with 1.7.0

**Comment by curtisy1** [comment]
I get an "update has stopped working" on 1.6.4 as well, but the large screen isn't appearing. Same error message in log.

**Comment by curtisy1** [comment]
Could it be that this issue is unrelated to headset? I decompiled the Squirrel update.exe and it's crashing internally (see screenshot), so maybe it's best to submit an issue on the squirrel repo since we all get the same error?
![squirrel_updater](https://user-images.githubusercontent.com/23632152/37248025-af153d10-24c6-11e8-96dd-bef09b8ea3a9.PNG)

**Comment by danielravina** [comment]
I don't even know what to ask this is so obnoxious. I'm not sure why every other version works for me without a problem

**Comment by fcastilloec** [comment]
I think this has to do with the fact that we are checking for an update on installation. I decided to uninstall Headset, delete all the AppData related to Squirrel and Headset, and any temp and log files and now this is what I'm getting when trying to install under Windows 7: [headset.log](https://github.com/headsetapp/headset-electron/files/1800001/headset.log)

**Comment by danielravina** [comment]
we just merged #130 to address this issue. Thanks @fcastilloec for putting the time to research and trying out different solutions!

**Comment by curtisy1** [comment]
Working! Thank you!
