### ISSUE TITLE
Search by ID

### ISSUE THREAD

**Issue by e-orlov** [headsetapp/headset-electron#131]
### Is it a bug or is this feature just not yet implemented?

I'm trying to search a certain playlist by its ID from the youtube url, but fail on this - Headset is never ending the search.

If this isn't implemented yet - please make it with high prio:) It could be pretty tricky to find a playlist, specially if it has a common title, like `reggae sets`. With search by ID it would be a nobrainer.

**Comment by danielravina** [comment]
You can search playlist if you remove the `v=...` from the ur or only use the ID
e.g
👍PL3WxO0HXyeYvTHDKY-kNDCnLjn1DTEtT6  
👍https://www.youtube.com/watch?list=PL3WxO0HXyeYvTHDKY-kNDCnLjn1DTEtT6  
👎https://www.youtube.com/watch?v=LSzjbJLpVbM&list=PL3WxO0HXyeYvTHDKY-kNDCnLjn1DTEtT6  

Hope that helps solve your problem?

**Comment by danielravina** [comment]
@e-orlov I will close this issue now, feel free to reopen if the solutions above are not working for you. Thanks!
