### ISSUE TITLE
Volume is always being set to zero after play/pause

### ISSUE THREAD

**Issue by Mebus** [headsetapp/headset-electron#135]
![screenshot_20180323_115941](https://user-images.githubusercontent.com/271557/37825900-b497123e-2e91-11e8-89a9-d42a05301444.png)

After hitting pause and play the volume of the headset app is always being set to zero. I am using Fedora 27 with KDE. The volume should not be affected by play/pause. My Heaset Version is 1.7.0.

I attached a screenshot of the volume control panel.

Thank you for the App and your help.

Mebus

🖼

**Comment by Mebus** [comment]
Hi!

It says: "Version: Core: 1.7.4, Wrapper: v1.7.0". It's the default KDE volume controller. I am pressing the buttons directly inside the App. There is no such key on my keyboard.

Mebus

**Comment by fcastilloec** [comment]
Hey Mebus, I'm sorry but I can't reproduce this. I just install Fedora 27 with KDE, updated all packages to their latest version and installed Headset and tried pausing it in every way possible and nothing.
This seems to be a bug with your specific configuration. Also, when using Headset you can see the name of the app itself on the volume controller but your image doesn't.
I would suggest reinstalling Headset, and also deleting the directory `~/.config/Headset` so no cache or configuration is stored.

![screenshot_20180323_155657](https://user-images.githubusercontent.com/1280530/37856846-1a840440-2ecd-11e8-8a07-b1471baabd2b.png)

**Comment by danielravina** [comment]
For the lack of response and ability to reproduce, I will close this issue now. @Mebus feel free to reopen at any time
