### ISSUE TITLE
App does not work through proxy 

### ISSUE THREAD

**Issue by tonyemiliano** [headsetapp/headset-electron#136]
### Description

We use the headset app at work. We have here an proxy firewall configured thats block headset app. 

### Expected behaviour

I need setup proxy settings on headset app. The configuration of proxy is authenticated, so is not possible bypass the headsetapp domains.

### Actual behaviour

Today every time we access headsetapp trought proxy an message error is showing in both windows

### Your Environment

- Linux Fedora 27
- Version:
Core: 1.7.2, Wrapper: v1.7.0

**Comment by fcastilloec** [comment]
This is a duplicate of #3 and #126
