### ISSUE TITLE
Description of DEB file shows Native Player for OSX

### ISSUE THREAD

**Issue by sikender** [headsetapp/headset-electron#14]

**Comment by danielravina** [comment]
😳
will fix that. sorry!

**Comment by sikender** [comment]
😁

**Comment by sikender** [comment]
Great work btw. Love your app. 👌

**Comment by danielravina** [comment]
Fixed in https://github.com/headsetapp/headset-electron/releases/tag/v1.5.3-linux future users won't see it. Thanks!
