### ISSUE TITLE
Playlist with repeat all on will not continue to next track

### ISSUE THREAD

**Issue by FelixVicis** [headsetapp/headset-electron#140]
### Description

When listening to a playlist with `Repeat All` on, playlist stops at the end of the first track listened to.

### Expected behaviour

Playlist should play through all tracks, cycling back to the first track at the end of the last.

### Actual behaviour

At the end of the first track listened to (does not matter what position in the playlist the track is at),
the song will pause at the last second (eg `2:30` of `2:31`) and remain there indefinitely. 

Video player shows recommended videos.

![image](https://user-images.githubusercontent.com/6580094/38521174-c4a4428a-3bf9-11e8-8c33-63c514338d6a.png)

### Your Environment

- Ubuntu 14.04
- Core: 1.8.1, Wrapper: v1.7.0

**Comment by fcastilloec** [comment]
I can confirm this bug. It seems that the songs stops one second before it's finished. In the previous screenshot, you can see it's stuck at `2:30` and the length of the song is `2:31`

**Comment by danielravina** [comment]
Thanks for reporting!
bug fixed in Core: 1.8.2

Restart the app to get those changes.

**Comment by FelixVicis** [comment]
Awesome work @fcastilloec and @danielravina!
Love the fast response.
