### ISSUE TITLE
RPM support

### ISSUE THREAD

**Issue by joseluisq** [headsetapp/headset-electron#15]
Currently, it's available the Debian package only ([Headset_1.5.2_amd64.deb](https://github.com/headsetapp/headset-electron/releases)) for GNU/Linux systems.
It would be great if you can offer support for RHEL-related systems such as Fedora x86_64.

**Comment by danielravina** [comment]
Hi @joseluisq, Yes we _officially_ support ubuntu due to lack of time on my end, I didn't release for other distros. you can follow the readme to build it for RHEL. I should change the website to not say "Linux" as this is misleading.

**Comment by joseluisq** [comment]
@danielravina 
> I should change the website to not say "Linux" as this is misleading.

Yep, because I use Fedora and I didn't find the `.rpm` to try Headset :smile: 

Here an idea for website fix. https://atom.io/
![image](https://cloud.githubusercontent.com/assets/1700322/26159906/1e13fe0e-3b20-11e7-96bf-25e3f20197c6.png)

I hope in the future you can support it.
Anyway, I will try to build from the source.

**Comment by dlasalle** [comment]
If you're interested, you can generate packages for Arch, Fedora, Centos, and Ubuntu via BytePackager (https://bytepackager.com) with the following settings:

Build Instructions
```
npm install --no-optional
"$(npm bin)/electron-packager" . --ignore=node_modules/electron-prebuilt \
--ignore=node_modules/electron-packager   --out build/   --overwrite   --platform=linux \
--arch=x64
```

Install Instructions
```
install -d -m755 "@INSTALL_PREFIX@/usr/lib/"
install -d -m755 "@INSTALL_PREFIX@/usr/bin/"
cp -r "build/Headset-linux-x64" "${BP_DESTDIR}/usr/lib/headset"
ln -s "/usr/lib/headset/Headset" "${BP_DESTDIR}/usr/bin/headset"
```

And set the dependencies to `nodejs` and `npm` for each distribution (and additionally `nodejs-legacy` for Ubuntu).

**Comment by joseluisq** [comment]
Cool thanks :+1

**Comment by ishubhamsingh** [comment]
The method described by @dlasalle works like charm,using the app on my Arch.Thanks @joseluisq  for this awesome app.

**Comment by pavanjadhaw** [comment]
Create Headset.desktop file in /usr/local/applications

`**[pavan@spiritualcraft ~]$ cat /usr/share/applications/Headset.desktop**
Exec=/usr/bin/headset -- %u
Icon=/usr/lib/Headset/resources/app/icon.png
Terminal=false
StartupWMClass=headset
Type=Application
Categories=Network`

**Comment by m1guelpf** [comment]
@pavanjadhaw Already said in #11

**Comment by bil-elmoussaoui** [comment]
@danielravina just use travis & make it build all the packages you want for you ;)

**Comment by danielravina** [comment]
@bil-elmoussaoui will it be hard to setup?

**Comment by bil-elmoussaoui** [comment]
@danielravina Not at all, Ubuntu (used by Travis) has great support for nodejs and npm, as you can install them directly from the ubuntu repository without having any issues to configure them. The rest can be done using electron-builder npm package with can build your application for a lot of packages formats on Linux like : .deb (Debian), .RPM, .pacman .appImages, .snap 
I can help here if you just configure travis with your repository and i will try to create a working PR for you :+1:

**Comment by danielravina** [comment]
That would be awesome! much appreciated. I'm going to do some changes with the branches. currently it's `master` (mac), `master-linux` and `master-windows`. I'll merge them all into master and create sub-directories for the OS. It will be a lot easier to manage, I think

**Comment by danielravina** [comment]
Fixed and available in https://github.com/headsetapp/headset-electron/releases/tag/v1.6.0-linux 🎉

**Comment by joseluisq** [comment]
Awesome! :+1:
