### ISSUE TITLE
Cant run the app on the arch Linux x64

### ISSUE THREAD

**Issue by Cross03** [headsetapp/headset-electron#16]
Hey i just build the app from the source. But when trying to execute the binary file i got error of missing module
![selection_094](https://cloud.githubusercontent.com/assets/16729502/26148889/62ca91d2-3b22-11e7-9494-71025a609823.png)

But i'm sure, i have the electron-default-window installed

![selection_095](https://cloud.githubusercontent.com/assets/16729502/26148915/7c05e37c-3b22-11e7-95dc-179179e545e4.png)

**Comment by danielravina** [comment]
What's your node version?

**Comment by hoshi411** [comment]
I was a bit more successful by adding  `--electron-version=1.6.8` to the end of this command , as in:

`sudo electron-packager .   --ignore=node_modules/electron-prebuilt   --ignore=node_modules/electron-packager   --out build/   --overwrite   --platform=linux   --arch=x64 --electron-version=1.6.8
`
Also , obvious things like git cloning the project were included in the readme file while more important and much less obvious things were neglected, such as.....

After running the electron-packer command, how do I install the binary and the .desktop file ?!?!?!

Also, it should be included that before running `sudo electron-packager`  you need to cd into the git cloned project folder.

Please tell me how to build this and get it running. I have built many projects with `make install` but have never experienced electron before. How do we make the final install after doing `electron-packager` ?

Thank you.

**Comment by danielravina** [comment]
@hoshi411 
> After running the electron-packer command, how do I install the binary and the .desktop file ?!?!?!

The installer depends on your system. As mentioned in step 4, for Debian systems, we use `electron-installer-debian` as part of the automated build. Did not add instructions for other systems since I havn't tried it myself. Seems like @dlasalle made it in https://github.com/headsetapp/headset-electron/issues/15#issuecomment-302519087 If it works for you, I can add that to the instructions.
As for the `.desktop`, it's in the Known issues part in the Readme

> Also, it should be included that before running sudo electron-packager you need to cd into the git cloned project folder.

True. I neglected the `cd`. Will add it as a step. Is there a reason you use `sudo`? I don't believe it's necessary.

**Comment by danielravina** [comment]
@Cross03 can I close this issue?

**Comment by PrzemekSkw** [comment]
Hi, app works great on arch, just download deb package and convert it with command (first install archalien):
_archalien Headset-1.5.4-1.deb_
then install new package:
_sudo pacman -U headset-1.5.4-1.pkg.tar.gz_

**Comment by danielravina** [comment]
Thanks @PrzemekSkw I think this can be closed if your instructions.

**Comment by PrzemekSkw** [comment]
@danielravina hi, headset is now in AUR repository :)

**Comment by FabioLolix** [comment]
Hi @danielravina 
I'm the AUR packager for the binary version of headset, built from the Debian package

It would be nice if you write that can be installed with "yaourt -S headset-bin" or equivalent on Arch & derivates
