### ISSUE TITLE
Email confirmation issue

### ISSUE THREAD

**Issue by abZameen** [headsetapp/headset-electron#162]
### Description

My email is not confirmed so I am asked to confirm the email by a notification bar at the bottom of the app. When I click on it a popup is opened with a message saying email is sent and a textfield where I can enter the code received in the email. 

### Expected behaviour

I should get an email with activation code which on entering in the popup's textfield will confirm my email and that'd be it.

### Actual behaviour

I never get an email and clicking **Resend** option on the popup takes you to a loader which never ends (I believe the app crashes there.) 

### Your Environment

- macOS High Sierra - v10.13.4 
- Core: 1.9.1, wrapper: v1.9.0

### Screenshots

![screen shot 2018-05-20 at 1 10 34 pm](https://user-images.githubusercontent.com/8578353/40276933-56d0b544-5c2f-11e8-85b8-71a8c57f3da5.png)

**Comment by danielravina** [comment]
The resend code is indeed a bug. I just fixed it (updated in core 1.9.2)

For the email issue, I'll need to look into it. do you mind sending your email to hello@headsetapp.co and we can continue the discussion there? 

Thanks!
