### ISSUE TITLE
Scale preview window

### ISSUE THREAD

**Issue by espilsad** [headsetapp/headset-electron#164]
Is it possible to scale the video player automatically to the size of the window?
<img width="1055" alt="screenshot 2018-05-24 13 31 35" src="https://user-images.githubusercontent.com/17473295/40482996-d17d65e2-5f56-11e8-838c-6045e149ca53.png">

**Comment by danielravina** [comment]
you know what, I always assumed it's not possible but never actually checked it out. So I did check it out, and made a fix here #166

You'll see it shortly.
