### ISSUE TITLE
pro

### ISSUE THREAD

**Issue by M1lkshake** [headsetapp/headset-electron#170]
why did you limit the number of skips
if you kept that unlimited for all but still added the extra pro features i wouldn't have switched to spotify oof

**Comment by danielravina** [comment]
Thanks for the feedback. I respect your decision as I knew not everyone would stick on after this change.

Consider this though:
- Compare to the free Spotify, Headset has doubled the number of skips and doesn't show you ads;
- Headset Pro is 5 times cheaper than Spotify

🤷‍♂️

**Comment by sbernard31** [comment]
> Compare to the free Spotify, Headset has doubled the number of skips and doesn't show you ads;
> Headset Pro is 5 times cheaper than Spotify

Spotify remunerates artists.
Spotify has its own backend to maintain to store and stream musics.

It sounds like comparing apples and oranges ...
