### ISSUE TITLE
Can't activate Last.fm - loading forever

### ISSUE THREAD

**Issue by ronilaukkarinen** [headsetapp/headset-electron#181]
### Description

Trying to activate Last.fm by clicking "Connect", but after allowing it to connect, it gets back to Headset and loads up forever.

### Expected behaviour

It should activate/connect Last.fm.

### Actual behaviour

Loading forever.

### Your Environment

- What OS are you using?

macOS Sierra, 10.12.6

- What version of Headset? (copy and paste from the user profile page if possible)

2.0.0 (1.0.100)

### Screenshots

![](https://rolle.design/headsetapp-1.png "Screenshot")
![](https://rolle.design/headsetapp-2.png "Screenshot")
![](https://rolle.design/headsetapp-3.png "Screenshot")
![](https://rolle.design/headsetapp-4.png "Screenshot")

**Comment by ronilaukkarinen** [comment]
![](https://rolle.design/headsetapp-5.png "Screenshot")

**Comment by danielravina** [comment]
Thanks so much for reporting this. The problem is fixed now (core 2.0.14), might need to refresh your cache in the dev tools :)

**Comment by ronilaukkarinen** [comment]
Confirmed working, thanks!
