### ISSUE TITLE
Black and white icon on macOS menubar

### ISSUE THREAD

**Issue by ronilaukkarinen** [headsetapp/headset-electron#182]
### Description

The icon is colored but it would be better as black and white to match macOS guidelines.

### Expected behaviour

The icon should be black and white on menubar.

### Actual behaviour

The icon is colored on menubar.

### Your Environment

- What OS are you using?

macOS Sierra, 10.12.6

- What version of Headset? (copy and paste from the user profile page if possible)

Core: 2.0.14, wrapper: v2.0.0

### Screenshots

![](https://rolle.design/headsetapp-icon.png "Screenshot")

**Comment by mattt** [comment]
Here's a PDF containing a monochrome icon suitable to replace the existing menubar icon:

[headset-menubar-icon.pdf](https://github.com/headsetapp/headset-electron/files/2522132/headset-menubar-icon.pdf)

I'm unable to find guidance about menu bar icons in Apple's official documentation, but I believe that a PDF like this should work. If not, here's a 20x20 px PNG file that can be used instead:

![headset-menubar-icon](https://user-images.githubusercontent.com/7659/47608402-cf161500-d9e1-11e8-9fc7-383fa5750da6.png)

Here's a rough idea of what this should look like in context:

![menubar-mockup](https://user-images.githubusercontent.com/7659/47608409-eb19b680-d9e1-11e8-9745-e9419d88529e.png)

The current Headset icon doesn't lend itself to display at a small scale like this, and an ideal solution would involve creating a simplified waveform shape for low resolution images. In the meantime, I believe a proper monochrome icon would be a welcome replacement.

**Comment by fcastilloec** [comment]
@mattt Thanks for the pdf, it looks great!

Right now the only guide to icons is [this site](https://developer.apple.com/design/human-interface-guidelines/macos/icons-and-images/image-size-and-resolution/).
We are currently using 3 icons, each for different pixel densities. We need a `64x64px`, `32x32px` and `16x16px`, all are `png`.
You can check them out in [`darwin/icons`](https://github.com/headsetapp/headset-electron/tree/master/darwin/icons), they're named `Headset.png`, `Headset@2.png` and `Headset@4.png`. They all have transparent backgrounds.
If you could provide those 3 resolution icons based on your `pdf`, that would be much appreciated!
