### ISSUE TITLE
Cannot access main window

### ISSUE THREAD

**Issue by violentswami** [headsetapp/headset-electron#183]
### Description

After installing the application only the player window is opening, the main navigation window will show up in available windows but clicking it does nothing

### Expected behaviour

Clicking the window should make it appear / it should appear after launching the application

### Actual behaviour

The window does not appear anywhere on the screen after being clicked, nor does the use of any movement keys e.g. Win + left 

### Your Environment

- What OS are you using? Windows 10
- What version of Headset? 2.0.0

### Screenshots

🖼
![2018-07-10 09_48_20-new issue headsetapp_headset-electron](https://user-images.githubusercontent.com/41050483/42499431-b1ea2ee6-8426-11e8-89cb-3566f4b24cc0.png)
![issue1](https://user-images.githubusercontent.com/41050483/42499539-f6883700-8426-11e8-9d04-0d0e348b358c.png)

**Comment by danielravina** [comment]
Sorry, I wasn't able to reproduce your issue on Win 10. We just released a new Windows build https://github.com/headsetapp/headset-electron/releases/tag/v2.0.1 which downgraded electron due to this issue https://github.com/electron/electron/issues/13043 please check if it _may_ possibly fix your problem

**Comment by violentswami** [comment]
Hi Daniel,

Thanks for the response, unfortunately this han't fixed the issue, two more pieces of information that may be of note:

- I'm using a PC at work (however I have admin install rights), this was not an issue with my older work PC running windows 7
- I get the following message before attempting to install the program:
![error](https://user-images.githubusercontent.com/41050483/42566538-d40b7358-84fe-11e8-8d3c-d18f84fadb71.png)
