### ISSUE TITLE
return [object  Object] after payment (start your 30 days trial)

### ISSUE THREAD

**Issue by lichingchester** [headsetapp/headset-electron#188]
### Description

as the title

### Expected behaviour

display text

### Actual behaviour

<div style="background: red">[object Object]</div>

### Your Environment

- macOS High Sierra (version 10.13.5)
- Version: Core: 2.0.14, wrapper: v2.0.1

### Screenshots

![screen shot 2018-07-18 at 7 08 44 pm](https://user-images.githubusercontent.com/23126132/42878000-1ae4fbcc-8abe-11e8-9917-981a5170d3a2.png)

**Comment by danielravina** [comment]
Thanks for reporting this! Do you happen to remember what field was wrong/missing when you go that?
