### ISSUE TITLE
Likes have reset to 0

### ISSUE THREAD

**Issue by FelixVicis** [headsetapp/headset-electron#189]
### Description

Opened up the app and I have no more likes. Previously had 30 or so songs 'liked' and now there are none.

### Expected behaviour

Likes should persist. 

### Actual behaviour

There are no likes
![image](https://user-images.githubusercontent.com/6580094/43680617-4332acae-97f3-11e8-94a5-396fd30a918a.png)

### Your Environment

- OS: Ubuntu 16.04
- Core: 2.1.0, wrapper: v2.0.0

### Screenshots

![image](https://user-images.githubusercontent.com/6580094/43680628-6c65eaaa-97f3-11e8-921b-55e44039c80a.png)

**Comment by danielravina** [comment]
@FelixVicis can you let me know your account email? please send it to daniel@headsetapp.co.

**Comment by danielravina** [comment]
Sorted it out with @FelixVicis. Due to high usage, the limit on reads was reached. I increased the read capacity of the DynamoDb instance. After restart, the likes were back.
