### ISSUE TITLE
Offer a Yearly Plan

### ISSUE THREAD

**Issue by kcnickerson** [headsetapp/headset-electron#192]
### Description

Yearly pricing plan for Pro.

### Expected behaviour

I should be able to pay $19.99 up front for an annual plan.

### Actual behaviour

My credit card gets "littered" with $1.99 purchases per month.

### Your Environment

Ubuntu / Latest
Headset / Latest (Free)

### Screenshots

N/A

**Comment by danielravina** [comment]
Hi @kcnickerson,

Luckily, we were just in the midst of a yearly plan rollout and with that, making some changes in the pricing.
Current prices are as follows:
$2/month - billed $24 yearly
$3/month - billed month-to-month

This is to encourage more people to have a yearly subscription and avoid littered purchases.

As of now, you can subscribe to a yearly plan through the app

Thank you very much for your support!
