### ISSUE TITLE
Update 2.0.2 breaks javascript

### ISSUE THREAD

**Issue by kurayamiyousei** [headsetapp/headset-electron#196]
When trying to run the new updated version from 2.0.1 to 2.0.2 it causes the following error;

Uncaught Exception:
TypeError: Cannot read property 'startsWith' of undefined
   at Object.<anonymous>
(C:\Users\name\AppData\Local\headset\app-2.0.2\resources\app.asar\lib\headsetTray.js:8:3
   at Object.<anonymous>
(C:\Users\name\AppData\Local\headset\app-2.0.2\resources\app.asar\lib\headsetTray.js:49:
   at Module._compile (module.js:569:30)
   at Object.Module._extensions..js (module.js:580:10)
   at Module.load (module.js:503:32)
   at tryModuleLoad (module.js:466:12)
   at Function.Module._load (module.js:458:3)
   at Module.require (module.js:513:17)
   at require (internal/module.js:11:18)
   at Object.<anonymous>
(C:\Users\name\AppData\Local\headset\app-2.0.2\resources\app.asar\lib\headsetTray.js:10:21)

Downgrading back to 2.0.1 runs fine, but then causes the error to pop up once the program detects the newer version and asks to download it.

**Comment by danielravina** [comment]
The error has been fixed on https://github.com/headsetapp/headset-electron/releases/tag/v2.0.3

Unfortunatelly, you'll have to re download it to work as the error prevents the auto update from running
