### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by m1guelpf** [headsetapp/headset-electron#2]
I'd love to help translating headset to Spanish.
(I open the issue here because it seems that the repo with the source is private...)

**Comment by danielravina** [comment]
Thanks for the offer and willingness to help, I truly appreciate at! ❤️ 
At the moment, I'm not planning on localizing the app (just yet). Will let you know for sure when this becomes a priority!

**Comment by m1guelpf** [comment]
@danielravina Cool!

**Comment by roadrunner** [comment]
if you plan so, i can help with the Turkish translation as well..

**Comment by danielravina** [comment]
We support Spanish! 🇪🇸

**Comment by fcastilloec** [comment]
@roadrunner if you want to help translating the app into Turkish, check [headset-locales](https://github.com/headsetapp/headset-locales)
We're in the process of adding documentation so it'll be easier for anybody to contribute, you can check the [fixes](https://github.com/headsetapp/headset-locales/tree/fixes) branch which is almost done and has the necessary information for you to start helping.
