### ISSUE TITLE
Play/Pause, Rewind, Fast forward buttons not working on macOS Mojave

### ISSUE THREAD

**Issue by woohoou** [headsetapp/headset-electron#206]
### Description

After upgrade to mojave in mac os the buttons Play/Pause, Rewind, Fast forward stop working.

### Expected behaviour

Should work as expected.

### Actual behaviour

The buttons work on itunes.

### Your Environment

- macOS Mojave 10.14 (18A391)
- Core: 2.1.15, wrapper: v2.0.5

### Screenshot

N/A

**Comment by danielravina** [comment]
Thanks for reporting this! Mojave now requires apps to explicitly grant permission to use media keys. From your system settings, go to privacy & security, find Headset in the accessibility tab and mark it.

![dpmwfuau0aeqdro](https://user-images.githubusercontent.com/3150871/48013993-842f8800-e0da-11e8-8b68-93a40142f269.png)

**Comment by woohoou** [comment]
It work, thanks!.

**Comment by waldyrious** [comment]
Adding this note in case this helps others: I had granted the accessibility permissions to the Headset app, but still, whenever I used the media keys, iTunes opened instead. After restarting the Headset app, it now works as expected. So I guess after granting the permissions, the app needs to be restarted.

**Comment by igauravsehrawat** [comment]
It works only when screen is unlocked.

On lock screen, I can't pause music from headset. Anyone else facing same issue?

Thanks
