### ISSUE TITLE
[Question] How much of this if Free Software?

### ISSUE THREAD

**Issue by asddsaz** [headsetapp/headset-electron#208]
**Question**: Just how much of Headset is [Free Software/FLOSS](https://en.wikipedia.org/wiki/Free_software)? Is any of it fully [proprietary/closed source](https://en.wikipedia.org/wiki/Proprietary_software)? If so what portion?

Does Headset still have to execute proprietary JS[1](https://www.gnu.org/philosophy/javascript-trap.html)?

**Comment by fcastilloec** [comment]
Headset has two parts for it to work,  you probably have seen them under your Profile page. The first is the `wrapper`, which is what this repository is about. The `wrapper` is open-source, anybody can do whatever they want with the code, and many people have contributed to it. The code is govern under a MIT license that you can find on the root of the repository.

The second part is the `core`, which is the app itself. This is loaded onto the main window. This part of the software is not open-source, it's proprietary. The only external request made by the `core` is to our [`headset-locales`](https://github.com/headsetapp/headset-locales) repo so we can load translations for the app, this uses the [`i18next-fetch-backend`](https://github.com/perrin4869/i18next-fetch-backend) module.

The `core` is design so it will only run under our `wrapper` (any other browser won't work), but the `wrapper` can easily (and freely) be modified to load any other app/site.
