### ISSUE TITLE
Javascript error ocurred

### ISSUE THREAD

**Issue by adiict0** [headsetapp/headset-electron#22]
Hi guys, first of all great app. Second.. im having some issues since the second day i use this app.
I think a made a mistake trying to close the youtube window. I dont remember the first error but it was a message saying that i cant close that window, after that the player stop working, i try to close and open again but now the all app was white, working but full white and i cant do anything, try to install everything again but nothing.
Another thing s that when i close this two white windows this s the message that the program gives to me.
A JavaScript error occurred in the main process
Uncaught Exception:
TypeError: Cannot read property "close" of undefined
 at BrowserWindow.win.on
(C:\Users\MyAccName\AppData\Local\Headset\app-1.5.2\resources\app\index.js;203:11)
 at emitOne (events.js:96.13)
 at BrowserWindow.emit (events.js.188:7)

Other way to said i cant use the app anymore :(

**Comment by danielravina** [comment]
Hi @adiict0, I'm sorry you are experiencing this issue. The small window is "protected" from closing but it's not 100% safe guarded so there might be a race condition of some kind. I will look into it. Silly question, did you uninstall the app before reinstalling it? If you completely remove all the files, the app will not remember the state you were in so technically you shouldn't see this error again.

**Comment by adiict0** [comment]
Hi Daniel, thanks for the reply. Yes i remove every single file.
Now i shut down the computer and start it again and now its working well. I
dont know why but its working, if i have some issue again ill be texting
you guys, thanks again and keep ip up with this!

2017-05-27 20:52 GMT-03:00 Daniel Ravina <notifications@github.com>:

**Comment by danielravina** [comment]
Cool! Will close the issue then. Will look into it and see if I can reproduce. Thanks for signing up for GitHub just to report it!
