### ISSUE TITLE
Install on Debian 10 “Buster”

### ISSUE THREAD

**Issue by Ghostbird** [headsetapp/headset-electron#222]
### Description

The package `libgconf2-4` that headset depends on is available in Debian 8, 9 and _unstable_
 from _oldlibs_.  In Debian 10 the headset .deb package is uninstallable
### Expected behaviour

Headset's .deb package should be installable on Debian 10

### Actual behaviour

The package manager complains – rightly – that the dependency `libgconf2-4` is unsatisfiable

### Your Environment

- Debian 10 “Buster”
- Headset v2.1.1 (.deb package)

### Solution

Run this script to install `headset` v2.1.1 on Debian 10
```bash
tmp=tmp-$(date +%s)
wget https://github.com/headsetapp/headset-electron/releases/download/v2.1.1/headset_2.1.1_amd64.deb
mkdir $tmp
dpkg-deb -R headset_2.1.1_amd64.deb $tmp
sed -i 's/libgconf2-4/libgconf2-4|libgconf-2-4/' $tmp/DEBIAN/control
dpkg-deb -b $tmp headset_2.1.1_amd64.deb
rm -r $tmp
sudo dpkg -i headset_2.1.1_amd64.deb
rm headset_2.1.1_amd64.deb
```
What does it do?
* Download headset 2.1.1 installer .deb
* Extract it to a temporary folder
* Modify the dependency list to demand _either_ `libgconf2-4` or `libgconf-2-4` (the new name for this package)
* Repackage the .deb file
* Clean up the temporary folder
* Install the headset.deb (prompting you to enter your password if required for `sudo`)
* Remove the headset.deb file (you no longer need it)

### Request

Please use `libgconf2-4|libgconf-2-4` as dependency for libgconf 2.4 in future deb packages so it installs on all versions of Debian.

**Comment by fcastilloec** [comment]
Thanks for reporting this. This is an issue that affects all packages build with `electron-installer-debian` and maybe `electron-installer-redhat`
I fix will come soon.

**Comment by Ghostbird** [comment]
I have no idea why I used the old v1.6.1 when I reported this. v2.1.1 is affected in the same way, and I have updated the original post to reflect this.
> This is an issue that affects all packages build with `electron-installer-debian`…
When I run this script that automates the build process as described in `README.md`:
```bash
sudo apt-get install libdbus-1-dev libglib2.0-dev
sudo npm install -g electron-packager electron-installer-debian
git clone https://github.com/headsetapp/headset-electron.git
cd headset-electron/linux
git checkout v2.1.1
npm install
electron-packager . \
  --executable-name headset \
  --ignore "(bin|Procfile|sig|gh-pages)" \
  --prune true \
  --out build/ \
  --overwrite \
  --asar \
  --platform=linux \
  --arch=x64
electron-installer-debian --src build/Headset-linux-x64 --dest build --arch amd64
sudo dpkg -i build/headset_2.1.1_amd64.deb
```
It does not depend on any `libgconf`. I'm not sure why, though. The dependencies listed in the control file are: `libgtk-3-0, libnotify4, libnss3, libxss1, libxtst6, xdg-utils, kde-cli-tools | kde-runtime | trash-cli | libglib2.0-bin | gvfs-bin` However, I have no knowledge of the packaging process, and do not know whether the generated list of dependencies is correct.

**Comment by fcastilloec** [comment]
@Ghostbird can you try the new version and see if it works?

**Comment by Ghostbird** [comment]
Works perfectly! Thanks!
