### ISSUE TITLE
Headset processes still active after closing the App (Ubuntu)

### ISSUE THREAD

**Issue by truscellino** [headsetapp/headset-electron#23]
Hi,
I am using Headset on Elementary OS Loki (based on Ubuntu 16.04.2). Everything up-to-date as of 28th May 2017.
After closing the app, the Headset-electron process is still there and using memory, and if I re-open and re-close, there are 2 processes etc. etc.
So there must be something wrong with process management...
Thanks, Marc

**Comment by danielravina** [comment]
Hi Thanks for reporting. Seems like this is a bug in Chromium. I couldn't find a way to resolve this. The workaround is killing the process manually when the app quits. I was able to reproduce this in Windows as well but not in Mac. Released a new build for both. Do you mind testing this out? https://github.com/headsetapp/headset-electron/releases/download/v1.5.4-deb/Headset_1.5.4_amd64.deb

**Comment by truscellino** [comment]
Hi - that was a quick response!
I have downloaded and tried the 1.5.4 and the workaround works fine for me. All Headset processes effectively disappear when closing the app.
Thank you.

**Comment by danielravina** [comment]
Awesome! I actually started investigating this yesterday after https://github.com/headsetapp/headset-electron/issues/22. The error occurred because of the orphaned processes.
