### ISSUE TITLE
Repeat One + Media Next or Next Track replays same song or jumps to bugged Upgrade To Pro commercial

### ISSUE THREAD

**Issue by schroedingersKat** [headsetapp/headset-electron#231]
### Description

When playing song with Repeat One option, if user presses Media Next key or Play Next button, Headset starts playing same song from beginning. If at this moment Upgrade To Pro commercial pops up, it gets stuck in Repeat One mode and user is unable to change Repeat mode.

### Expected behaviour

User should be able to skip songs normally, despite Repeat One button. Commercial should play once and then normal playback should resume.

### Actual behaviour

Skipping song replays same song. Done too many times shows Upgrade To Pro commercial which gets stuck in Repeat One mode. User is unable to change Repeat mode.

### Your Environment

- Windows 10, version 1803, build 17134.706
- Headset Core: 2.2.1, wrapper: 2.1.2

**Comment by danielravina** [comment]
Pushed a fix for that. Update version `Core 2.2.2`
