### ISSUE TITLE
Discord RPC support

### ISSUE THREAD

**Issue by ghost4499** [headsetapp/headset-electron#232]
Hello, I've recently been going through a bunch of apps for music streaming and I've come to like the layout of this one. I like to show others what i'm listening to and I was wondering if you guys could add an optional Discord rich presence?

**Comment by fcastilloec** [comment]
I'm not very familiar with Discord rich presence, but isn't Discord only for games?

**Comment by ghost4499** [comment]
Spotify uses the RPC as well but they're a bit more integrated with Discord, and some other third party apps like the Google Play Desktop or YouTube Music Desktop app (laggy) have an RPC showing (if i remember correctly) the artist, song, and remaining time left on the song.

**Comment by Rediowz** [comment]
It would be a really great enhancement ! I'm rooting for it

**Comment by fcastilloec** [comment]
It's been a while but discord support has been added. The next release will have it. If you want to try it before the release, check the README to see how.
I would really appreciate any feedback and if there are any problems/bugs, feel free to create a new issue here.
