### ISSUE TITLE
the menu doesnt show up when clicking the icon on the menu bar 

### ISSUE THREAD

**Issue by jjbully** [headsetapp/headset-electron#238]
### Description

the menu doesnt show up when clicking the icon on the menu bar 

### Expected behaviour

the menu or option will show up when clicking the icon on the menu bar

### Actual behaviour

the menu or option doesnt show up when clicking the icon on the menu bar

### Your Environment

- MAC OS 10.14.4
- 2.1.3

### Screenshots

![Cursor_and_Item-0_and_Item-0_and_AppleVolumeExtra_and_Item-0](https://user-images.githubusercontent.com/43172408/58615735-66cc4080-82ee-11e9-8a4d-1aa4783b5c76.jpg)

**Comment by fcastilloec** [comment]
Thanks for reporting this. It seems that the problem was a module we depend introduce some error. A fix will be coming really soon.

**Comment by fcastilloec** [comment]
There's a new release, v2.1.4, this issue should be fixed there

**Comment by jjbully** [comment]
thank you very much
