### ISSUE TITLE
Option to disable hardware acceleration

### ISSUE THREAD

**Issue by oL-web** [headsetapp/headset-electron#243]
### Description

All the existing Chromium apps allow the user to disable hardware acceleration. I always disable it because otherwise my GPU fans go crazy to 100% fan speed even for simple things like gifs on Discord. Same thing happens here with live music and it crashed my PC once already. I'm not sure if it happens only on my PC but still, the option is there in every other app. 

From what I've seen it's just a matter of calling a [simple function](https://github.com/electron/electron/blob/master/docs/api/app.md#appdisablehardwareacceleration).

### Your Environment

- What OS are you using? 
Windows 10

- What version of Headset? (copy and paste from the user profile page if possible) 
2.3.3

**Comment by fcastilloec** [comment]
I think the fastest way to implement this is allowing the user to pass an argument from the command line.
I'll look into it.

**Comment by danielravina** [comment]
would it work on Windows @fcastilloec ?

**Comment by fcastilloec** [comment]
@danielravina I think it will. I'll test it out when doing merging of the whole code

**Comment by danielravina** [comment]
v3.0.0 Now support disabling hardware acceleration via the command line. If you use Headset with [chocolatey](https://chocolatey.org/), you can run Headset with `--disable-gpu`

**Comment by fcastilloec** [comment]
Chocolatey is not required. Here's a very easy guide (with pictures) on how to add the `--disable-gpu` option to the Headset shortcut, the guide is for a video-game shortcut but it applies to any:
https://www.lifewire.com/command-line-parameters-video-games-3399930
