### ISSUE TITLE
Support Airpods

### ISSUE THREAD

**Issue by musa-almatri** [headsetapp/headset-electron#245]
### Description

Headset app is working fine with keyboard media keys. But, when I try to play and pause a song using the airpods it opens iTunes !!!

### Expected behaviour

Play and pause using the airpods should works like the media keys

### Actual behaviour

When trying to pause a song using the airpods itunes open 

### Your Environment

- What OS are you using?
macOS Mojave
- What version of Headset? (copy and paste from the user profile page if possible)
2.1.4
### Screenshots

🖼

**Comment by fcastilloec** [comment]
I don't think this is a problem with Headset but rather the configuration of your airpods. You should check the configuration under Bluetooth to see what pressing the buttons do and make sure they send media key shortcuts.
