### ISSUE TITLE
Duplicate songs after loading new tracks

### ISSUE THREAD

**Issue by SDVII** [headsetapp/headset-electron#247]
### Description

Pressing "LOAD MORE" while listing to a long playlist causes songs from the one you are listing to till the last to entry to be duplicated and added to the playlist before the newly loaded songs

### Expected behavior

It should not duplicate previously listed song and to load new songs correctly

### Actual behavior

Songs between the one currently playing till the last entry are duplicated and added to the playlist before the newly loaded songs

### Your Environment

- Windows 10
- 2.3.6

### Screenshots

![image](https://user-images.githubusercontent.com/10416702/60722933-eb882b00-9f3a-11e9-9283-35836d53e413.png)

**Comment by fcastilloec** [comment]
Sorry for not replying earlier. I haven't been able to duplicate it on my side. Do you still experience this? If so, can you provide a playlist where this is happening?

**Comment by fcastilloec** [comment]
Haven't heard back about this issue and hopefully the new release fixes it. If you're still experiencing this problem, feel free to re-open the issue.
