### ISSUE TITLE
Personal thoughts about search autocomplete

### ISSUE THREAD

**Issue by latteyo** [headsetapp/headset-electron#248]
### Description

I am using the HeadSet application very well and it seems that the function of autocomplete with the mouse cursor when searching is a little inconvenient.

What do you think about removing the autocomplete function due to the mouse cursor?

### Expected behaviour

The mouse cursor automatically completes when searching.

### Actual behaviour

No error message.

### Your Environment

- What OS are you using? Window OS
- What version of Headset? (copy and paste from the user profile page if possible)

core 2.4.0, wrapper: v2.2.0

### Screenshots

![image](https://user-images.githubusercontent.com/46841257/60808425-37e59c00-a1c3-11e9-94bb-948a80176bdc.png)

![image](https://user-images.githubusercontent.com/46841257/60808554-8bf08080-a1c3-11e9-89bf-ef9cd324481a.png)

**Comment by danielravina** [comment]
@latteyo you know, this bug has been annoying me as well for quite some time. I knew it's a low-hanging-fruit bug to fix but didn't have the time to look over it. Happy to say it is now fixed on Core v2.4.4. 

Cheers!

**Comment by latteyo** [comment]
I checked. Thanks!
