### ISSUE TITLE
Ubuntu deserves a user interface as well.

### ISSUE THREAD

**Issue by oakniiv** [headsetapp/headset-electron#259]
### Description

Just watch the video.

### Expected behaviour
The app should work properly.

### Actual behaviour

It doesn't. Design I guess.

### Your Environment

- What OS are you using? Ubuntu 16.04
- What version of Headset? (copy and paste from the user profile page if possible)
3.0.2
### Screenshots 
Watch the video.
https://streamable.com/5rb8c

No bottom menu as in picture. No back button, the responsiveness just does not follow the app size.

**Comment by danielravina** [comment]
@oakniiv so sorry you are experiencing this. This might happen after v3.0.0 that caused some breaking changes. Do mind just trying to run an older version https://github.com/headsetapp/headset-electron/releases/tag/v2.2.0 if possible and let me know if you're noticing the same behavior?

**Comment by danielravina** [comment]
I'm running Headset 3.0.2 on an Ubuntu 16.04.2 VM and getting the app's full height. That's really odd.
![Screen Shot 2019-07-12 at 8 40 09 AM](https://user-images.githubusercontent.com/3150871/61140668-af941f00-a480-11e9-95ec-c3125b5ddd7d.png)

**Comment by fcastilloec** [comment]
I've tested the app on Ubuntu 16.04, 18.04, 19.04, Fedora 30, Linux Mint, Ubuntu Mate, and in all of them there's always a full window shown.
Even though the window is set as not resizable, maybe having `minHeight` might help.

@oakniiv Can you try something to see if this gets fixed? Can you run on a terminal: `rm -rf ~/.config/Headset` This will delete all the config files. Let me know if the window is still that size after that.

**Comment by oakniiv** [comment]
The problem is that I'm using fakexrandr to split my 4k TV into 5 seperate displays. The app works perfectly on my laptop (secondary display), and I'm able to start the app on my laptop and then put it on my big display and It'll work, but if I start it when the bigger display is on it cuts it in half for some reason. A resize feature would be great. Or a web-application, even better you could also easily make an android app out of it with webview.

**Comment by fcastilloec** [comment]
This might actually be an issue with fakexrandr rather than with our app. I think it's resizing the window even though it's set to never do that. We've set the size of the app without resizing as a design choice.
I have four monitors on my system (they are not simulated) and Headset opens without any problems in all of them, and they're all different brands and models.

**Comment by oakniiv** [comment]
It is an issue with fakexrandr for sure. Re-sizing the app would be awesome and more and more users are going to ask for that. However, I just wanted to say that you have to make an Android app. Right now Headset is nothing but music.youtube.com with an AdBlock which I'm using, I ditched Spotify for Youtube Music with AdBlock and NewPipe on Android.
A Spotify alternative for Android would be awesome, and again, you can easily charge $5 for that once it comes out, better that than raise the price later on.

**Comment by danielravina** [comment]
Regarding Android app: yes, that would be amazing to have it but unfortunately, not feasible. Please take a look at the FAQ https://headsetapp.co/docs/faq

**Comment by oakniiv** [comment]
> Unfortunately, not at the moment. There is no way currently to play YouTube videos while the phone screen is off, nor it’s possible to extract the audio and play it via the phone’s media player. Those restrictions alone discourage the team from building a mobile version.


Look at "new pipe", they have a background play option and it works perfectly.

**Comment by danielravina** [comment]
It’s technically possible but goes against ToS. They will be taken down at some point just like what happen to [streamus](https://www.google.com/amp/s/thenextweb.com/insider/2015/07/21/how-youtube-killed-an-extension-with-300000-users/amp/). I don’t want to take this risk.
