### ISSUE TITLE
[Request] Currently playing API

### ISSUE THREAD

**Issue by m1guelpf** [headsetapp/headset-electron#26]
Hi! I have a dashboard in my TV, that gets my currently playing song via LastFM and displays cover, title and album. It would be awesome if I could replace it with a Headset one, but it would need o have an API, where I can grab song details, or better, a webhook like triggers every time the song changes. Is this possible?

**Comment by m1guelpf** [comment]
If you want, I can setup and host a backend for this, that would work this way:
1- Headset has master keys to add new headset users to the application database, and the application returns an API key, that you can give the user if you want (or keep it hidden and make the users request it).
(Another option would be to store that token on the Headset database...)
2- After the code that sends the push notification of the new song, you post to the application the user ID and song details.
3- The user can get the current playing song and/or setup a webhook (this would be handled by the application)

As you see, my idea to make this possible, is to create a "middleware" that get's user details, and exposes an API to allow the users to get it. This would allow cool integrations like the one suggested, and I believe it would take only a little work from your side.
What do you think?

**Comment by danielravina** [comment]
Im planning on adding a last fm integration. You'll be able to sign in with the app and have the same effect on your TV. Would that work for you?

**Comment by m1guelpf** [comment]
@danielravina The LastFM integration would totally solve the problem!
Do you have an estimated release time? Thank you!

**Comment by danielravina** [comment]
Will probably be sometime this month

**Comment by danielravina** [comment]
lastfm scrobbling/now playing is ready. You can connect by clicking on the user icon on the top right! Let me know how it works for you!

**Comment by danielravina** [comment]
@m1guelpf can I close the issue?
