### ISSUE TITLE
Not an issue but better alternative, source to learn from for developers.

### ISSUE THREAD

**Issue by oakniiv** [headsetapp/headset-electron#261]
https://github.com/nukeop/nuclear

**Comment by fcastilloec** [comment]
I'm not sure what you're trying to say with this issue. Do you want Headset to look like nuclear? Do you want us to use nuclear source code for Headset?
In any case, nuclear is using `mps-youtube` to play videos but this goes against Youtube terms.  We are trying to go by what Youtube allows us to do, so we don't get shut down.

**Comment by danielravina** [comment]
LOL Love the testimonials 👍 
<img width="1403" alt="Screen Shot 2019-07-21 at 6 17 20 PM" src="https://user-images.githubusercontent.com/3150871/61600143-f81bad00-abe3-11e9-817b-4a4c3a0881f3.png">
