### ISSUE TITLE
Can't Change song position on My Collection

### ISSUE THREAD

**Issue by ajipw** [headsetapp/headset-electron#262]
### Description

Cannot move or shift songs in the collection.

### Expected behaviour

If I click and move down or up then it should be shifted.

### Actual behaviour

List of songs queues in my collection are rolled out but do not shift the song Queue, but instead become an html code

### Your Environment

- Windows 10 version 1903
- Headset 3.0.2 (core: 2.4.1, wrapper: v3.0.2

### Screenshots

![bug](https://user-images.githubusercontent.com/25083343/61596438-e959e800-ac2d-11e9-814d-e7b56d36d643.gif)

**Comment by danielravina** [comment]
I'm looking into it. it works in the "dev" mode which is weird.

**Comment by danielravina** [comment]
So only in the obfuscated bundle, I got an error `Uncaught ReferenceError: _0x5c28eb is not defined`. Not sure how and when it started happening. I replaced the obfuscator with terser-webpack-plugin and it's working now in version v2.4.3. Thanks for reporting this @ajipw!

**Comment by ajipw** [comment]
Thank you. It's working again now!
