### ISSUE TITLE
App stopped working

### ISSUE THREAD

**Issue by Prakhar236** [headsetapp/headset-electron#265]
### Description

It has been a month or so since the app stopped working. I have restarted my mac multiple times but still the issue persists. When I open the app, it just shows a blank gray box.

### Expected behaviour

It should open as normal so I can play and browse music

### Actual behaviour

The app opens but doesn't display a working screen.

### Your Environment

- What OS are you using? MacOS 10.14.5
- What version of Headset? (copy and paste from the user profile page if possible) 1.5.2

### Screenshots

![Screenshot 2019-08-11 at 7 19 02 AM](https://user-images.githubusercontent.com/22475424/62828611-5b5b9680-bc08-11e9-94cc-fa747394d957.png)

**Comment by danielravina** [comment]
1.5.2 is pretty old. can you try to download the latest version? https://github.com/headsetapp/headset-electron/releases/download/v3.0.2/Headset-3.0.2.dmg

**Comment by danielravina** [comment]
Just to clarify: you won't need to manually download and install every time there's a new version. We introduced the auto-update feature after 1.5.2
