### ISSUE TITLE
How about putting a search box under Likes Tracks?

### ISSUE THREAD

**Issue by latteyo** [headsetapp/headset-electron#268]
### Description

I think it would be nice to have a search box so that I can find it without having to scroll.

### Expected behaviour

putting a search box under Likes Tracks

### Actual behaviour

Not error, UI / UX Improvements

### Your Environment

- What OS are you using? Window
- What version of Headset? (copy and paste from the user profile page if possible)

Core: v2.5.2 Wrapper: v3.0.2

### Screenshots

![image](https://user-images.githubusercontent.com/46841257/63867467-d934e580-c9ef-11e9-9bd1-07ce27b8119a.png)

**Comment by danielravina** [comment]
Done!
