### ISSUE TITLE
Removing Tracks From Queues and Collections

### ISSUE THREAD

**Issue by merriander** [headsetapp/headset-electron#27]
I can see how to remove a track from a collection (selecting 'add to collection' and then 'unticking'), I cannot see how to remove one that is in a queue. Dragging and dropping to change the track order is possible, I would like to pick up a track I didn't want to hear and swipe it away off the queue. Possibly the same effect could be applied to tracks in a collection, the current method seems a little counter-intuitive as you are selecting add in order to take away.

**Comment by danielravina** [comment]
There is an open issue regarding the queue https://github.com/headsetapp/headset-electron/issues/4.
Interesting thoughts on the collections as well. I will add a "remove from collection" option as well. Thanks!

**Comment by danielravina** [comment]
Hi @merriander. Removing tracks from queue is now live! https://github.com/headsetapp/headset-electron/issues/4#issuecomment-312414145
