### ISSUE TITLE
Play media key opens iTunes when app is open but idle

### ISSUE THREAD

**Issue by marcopetreri** [headsetapp/headset-electron#270]
### Description

When the application is open but idle by some time, play media key is intercepted by iTunes.

### Expected behaviour

The app should continue to intercept the media keys as in active state.

### Actual behaviour

As in description.

### Your Environment

- macOS Mojave 10.14.4 (18E226)
- Headset wrapper 3.1.0 core 2.7.0

**Comment by fcastilloec** [comment]
I'll look into this but I can't reproduce this on Linux or Windows. It seems it might be a bug with electron itself and not Headset.

**Comment by fcastilloec** [comment]
@marcopetreri quick question. If you're still experiencing this issue, is your file system case-sensitive or not?

**Comment by fcastilloec** [comment]
Haven't heard back with any details about this bug. I'm closing it but if you are still experiencing this with the new version, feel free to re-open it.
