### ISSUE TITLE
No confirmation email

### ISSUE THREAD

**Issue by lfmac** [headsetapp/headset-electron#271]
### Description

No confirmation email every single time I ask for it, so I cannot confirm my account.

### Expected behaviour

There should be a confirmation email if we ask for it.

### Actual behaviour

It says an email was sent to my email address and to confirm the 6 digits code. 

### Your Environment

- MacOS Mojave 10.14.5
- Version 3.1.0 (3.1.0)

### Screenshots

![Captura de ecrã 2019-10-06, às 00 00 15](https://user-images.githubusercontent.com/35193672/66261822-4f392300-e7cc-11e9-9790-46bddd04ce68.png)

**Comment by danielravina** [comment]
Can you check the spam folder?
If it's not there, can you please send your email to hello@headsetapp.co and I'll activate it for you

**Comment by VerstandInvictus** [comment]
Mine got filtered to spam by gmail. Reported not spam, but you might want to follow that up with them.
