### ISSUE TITLE
Bad sound quality

### ISSUE THREAD

**Issue by ciases** [headsetapp/headset-electron#272]
### Description

Hello!
An app outputs silent muffled sound.

### Expected behaviour

Clean and loud sound.

### Actual behaviour

The music from the program is low quality and quiet. I tried to open certain tracks on youtube or via vlc, everything is fine (the sound is clear and loud). So something is wrong with the program (or with my system, haha) 

### Your Environment

- What OS are you using?
Linux Mint 19 Tara
- What version of Headset?
Core: v2.7.1, Wrapper: v3.1.0

**Comment by fcastilloec** [comment]
Can you provide a youtube link of the song that you were using to test? That way I can see what's happening, but so far, I can't reproduce this.
Because it's youtube, some songs are going to have bad quality because that's how they were uploaded.

**Comment by ciases** [comment]
Sorry for late response. I didn't see a notification.
Here is a link to test track: https://www.youtube.com/watch?v=NeQM1c-XCDc
After some tests I must admit that quality of audio is (probably) fine, but it's definitely quieter that other system sound. I need to increase volume up by 10% to get the same level as in mpv player (or vlc player).

**Comment by fcastilloec** [comment]
Headset has its own volume that usually starts around 75% if I remember correctly. Just make sure the app volume is to the max and you'll get the same level as other apps. I tested your song (awesome video btw) and the levels seem the same when Headset internal volume is maxed, compared to Chrome (or Firefox) volume.

**Comment by ciases** [comment]
Okay, I will recheck my system sound settings. Maybe mpv player has increased volume by default, he-he.
