### ISSUE TITLE
Export from command line

### ISSUE THREAD

**Issue by orangemango** [headsetapp/headset-electron#273]
Being able to export Headset data trough command line would open the possibility of some automation. I want to automaticaly download my liked tracks to sync them to my phone. 
(what is the current location and format of the user data ?)

(thank you for the app and the awesome "Play Similar Songs" feature!)

**Comment by fcastilloec** [comment]
I'm not 100% sure how you want this to work. We already have the possibility to download all your data from your Account tab, this includes all your likes. You can use this JSON object in your program to automate your sync.

**Comment by orangemango** [comment]
Yes the command line is to have access to the Export feature in the Account tab. It would looks like "headset.exe export db.json"

> (what is the current location and format of the user data ?)

I asked to know if there is already a way to extract the data without going trough the GUI.

**Comment by fcastilloec** [comment]
I'm sorry but I don't think this is possible. For this to happen, the way Headset works would have to change.
All the required functions to export your data reside on the GUI side. Even if we implemented a command line function, Headset will still have to open a window to get all the user data. There are also special cases to consider like the user isn't logged in.
Even though automation with Headset is technically possible, it's outside the scope of this project and might need a lot of time to implement. Unless @danielravina has an API, or shortcut, that I'm not familiar with, this is not something you'll likely see in the future.

As a far off workaround, I recommend you use [Spectron](https://github.com/electron-userland/spectron) to automate the process of getting to the user's page and downloading the data. This is definitely not ideal but if you're very committed to making this work, check the code in [test/app.test.js](https://github.com/headsetapp/headset-electron/blob/master/test/app.test.js) to see how we start the app. Then it's just a matter of navigating/clicking what you need using Spectron until you get your data.

**Comment by danielravina** [comment]
Thanks Felipe! that’s right, The reason you must use the GUI is because it authenticates with cookies instead of something more flexible like JWT. There is no official public API and I can’t promise there will be one any time soon.
