### ISSUE TITLE
Package for Flatpak?

### ISSUE THREAD

**Issue by Split7fire** [headsetapp/headset-electron#274]
Can it be possible to create a flatpak package? It will be all-in-one linux package as number of flatpak-ready linux distributions are growing.

**Comment by fcastilloec** [comment]
I've been looking into creating a flatpak but it seems it's not going to be possible. At the moment, there are no tools out there (that I know of) that support creating a flatpak for an electron app.
There's a package called `electron-installer-flatpak` but it hasn't been updated in 2 years.
Electron builder has some discussion in adding flatpak support but it's taken a long time for any work to be done there.
I'm going to leave this issue open just in case something changes in the future, but I'm labeling as `won't fix`

**Comment by x80486** [comment]
I tried to build it from sources...but that's going to take some time :confused:

If you are interested in publishing `Headset` right away, hopefully to Flathub, grab this branch: https://github.com/x80486/flathub/tree/co.headsetapp.Headset/ and send a Pull Request. I can do it for the first part though, but I can't commit to maintain it.

Let me know...the Flatpak on that branch works right now.

![image](https://user-images.githubusercontent.com/34633617/74112287-3f11c580-4b69-11ea-8151-ba0dcebf4791.png)

---

There are a couple of things that should be "fixed" later. Last but not least, I think it would be better if `Headset` would make use of Electron builder. The application is putting some files in non-usual locations, like the icons.

**Comment by rothgar** [comment]
AppImage may be a better alternative. [electron-builder](https://github.com/electron-userland/electron-builder) supports it as a target and unlike snap (ubuntu) or flatpak (fedora) it seamlessly works on either distro

**Comment by fcastilloec** [comment]
@rothgar feel free to open a PR to create a working AppImage.
I think that it'll be easier if we just provide a packaged `tar.gz` for Linux. This way you only have to uncompress it and run `headset`. No need for any proprietary/specific distribution system. Thoughts?

**Comment by rothgar** [comment]
I think you should do whatever is easiest for you to maintain. You lose some benefits with a tar (e.g. desktop launcher) but it's certainly portable and doesn't depend on a package manager.

**Comment by fcastilloec** [comment]
I think we can bundle a `.desktop` file inside and  `README` or `INSTALL` file with instructions.
Maybe I can create a script that when run, it modifies, copies the `.desktop` file, and update the database. This should only be run once, like an `install.sh`. It could also have an `--uninstall` option to delete that file.
I'll consider doing this for the next release. Right now we're trying to migrate from Travis/Appveyor to Github Actions and it's taking a little longer than expected.

**Comment by fcastilloec** [comment]
@rothgar @Split7fire there's currently a PR introducing flatpak support. Could you guys test it and see if there's any bugs, if so, please let me know.
Here's a [link to the artifacts](https://github.com/headsetapp/headset-electron/suites/942597122/artifacts/11674530), it will contain all of the Linux installers, including the `.flatpak`.
I'm still not familiar enough with flatpak to be able to submit it to flathub, maybe somebody with more experience can help with that.

**Comment by rothgar** [comment]
The .flatpak app worked for me. I had to still install flathub as a remote repo for the dependencies but otherwise it worked fine.

To submit it to flathub they have docs here https://github.com/flathub/flathub/wiki/App-Submission#how-to-submit-an-app

**Comment by fcastilloec** [comment]
@rothgar Thanks for testing!
I have seen those docs, the problem I have is with the manifest file. The official flatpack documentation regarding electron apps compiles the app from scratch, I want to be able to use the already compile app produce by `electron-packager`. Otherwise, the whole manifest is going to be a mess, and I can't guarantee that the compiled code will be the same as the `.deb` or `.rpm` installers.
I think I'm going to have to check the code of `electron-installer-flatpak` and `flatpak-bundler` and see how they do it, so I can recreate their manifest file and submit it.

**Comment by pizzadude** [comment]
It's live! 

https://flathub.org/apps/details/co.headsetapp.headset

Confirmed working in Fedora 32

**Comment by fcastilloec** [comment]
@pizzadude Thanks for testing. I've been working for the past days on trying to get it official on Flathub. @rothgar pointed out the details and the people from flatpak on their IRC channel were very helpful. I was about to post here the news, so more people can test it.
So, test it, and if there are any problems/bugs, just open a new issue here.

**Comment by pizzadude** [comment]
@fcastilloec BTW, if it weren't for the flatpak, I wouldn't of known this app existed. It helps with discovery.
