### ISSUE TITLE
Player not loading/initializing 

### ISSUE THREAD

**Issue by ZerGo0** [headsetapp/headset-electron#276]
### Description

A few days ago the headset application stopped working for me, the player doesn't seem load.

### Expected behaviour

The player should load and work just fine.

### Actual behaviour

It just doesn't load.

### Your Environment

- What OS are you using? Windows 10 build 1903
- What version of Headset? Core: v2.7.1, Wrapper: v3.1.0

### Screenshots

https://i.imgur.com/E5njzsv.png

**Comment by ZerGo0** [comment]
Nvm, my DNS blocklist filtered that domain, everything works fine after whitelisting it.

**Comment by tazkerino** [comment]
Hey, can you explain how you fixed this? I'm having a similar issue. Thanks
