### ISSUE TITLE
YouTube Searches Not Loading, Random Reddit Radio Stations Not Loading

### ISSUE THREAD

**Issue by Austint30** [headsetapp/headset-electron#277]
### Description

Headset App YouTube search no longer loads content. Certain Reddit radio stations are not available.

### Expected behaviour

Everything seemed to work fine until about a week ago. YouTube searches worked as expected, and reddit stations worked fine.

### Actual behaviour

YouTube searches frequently result in infinite loading times. Select Reddit radio stations do not load and result in an error message saying "\<subreddit\> is not available." This is happening on all of my devices.

### Your Environment

- Windows 10 Home 1903
- Core: v2.7.1, Wrapper: v3.1.0

### Screenshots

![Annotation 2020-01-04 221804](https://user-images.githubusercontent.com/16272815/71775122-e1260880-2f40-11ea-8b14-4189bb219e48.jpg)
![Annotation 2020-01-04 221843](https://user-images.githubusercontent.com/16272815/71775123-e1260880-2f40-11ea-9963-95c06b76a1e6.jpg)

**Comment by fcastilloec** [comment]
This is a weird bug. It's not always happening to me. I actually didn't notice it until I deleted all my cache.
@danielravina can you check if you're also experiencing this?

**Comment by danielravina** [comment]
API key has reached the daily quota every day since Dec 28. this is odd.
the reason it sometimes shows and sometimes not is because I'm alternating between two different keys to handle the load. I'll request a quota increase (again) and hopefully it will get approved in a timely manner.

**Comment by danielravina** [comment]
Ok just submitted a request. I'm not sure how long this will take this time. Last time I requested it took a few weeks. the patterns of usage do look odd. I can't tell if someone is abusing the API key as it has been consistently high (which is something I've never seen before).. but then again, last Jan the usage was quite high as well compare to the rest of the year so I guess we'll wait a few more days to see if it continues. Tomorrow (00:00 PST) it should go back to 0 and the app will continue working.

**Comment by danielravina** [comment]
I looked at the usage this morning, the quota was near the limit at around 11:00am. This is not normal. I generated a new API key with the same restrictions (domain) so things should be good for now. If this continues to be a problem I'll have to build a backend proxy server to handle youtube API requests which will essentially hide the key from the public. Maybe I'll do it via Cloudflare as they have built-in DDOS protection for free.

**Comment by Austint30** [comment]
Tried it this morning and the problem still persists.

**Comment by danielravina** [comment]
All limits are up using 3 API keys. the app is basically unusable until I hear back from Google.

**Comment by danielravina** [comment]
We've made some changes - please follow this guide to make Headset functional again: https://github.com/headsetapp/headset-electron/wiki/Get-Youtube-API-Key

Honestly, I wish I wouldn't have to do this, but there isn't really much choice at this point.
