### ISSUE TITLE
New API Entry Not Working

### ISSUE THREAD

**Issue by Kandelai** [headsetapp/headset-electron#279]
### Description

Apparently now you have to create a Google/Youtube API code and plug it into Headset. I went through the steps as directed to create a new API Code, entered it into Headset, but I keep getting Invalid Code Error. The Code on Google says active. I waited many hours and tried several times to enter the code, but same Invalid Error occurs.

### Your Environment

I am using Manjaro OS (Arch-based), KDE, Stable Release. 
Headset version in AUR reads 3.1.0-1

**Comment by fcastilloec** [comment]
I've tested with multiple accounts and keys and they all work. Make sure you copy/paste the correct code. Also, make sure that you created an "API key" and not an "OAuth client ID" and you haven't added any restrictions.
It should look like this:
![Selection_023](https://user-images.githubusercontent.com/1280530/71931484-b0b5b880-3152-11ea-820e-0de034da3bf4.png)

**Comment by Kandelai** [comment]
I actually typed it the API Key this time and still get 'Key is Invalid. Please try again.' I did create an 'API Key' and not an 'OAuth client ID'. No restrictions. I will attach a screenshot.


![Screenshot_20200107_161845](https://user-images.githubusercontent.com/39681298/71940126-15c8d880-316a-11ea-95d0-b831648e3a80.jpg)

**Comment by fcastilloec** [comment]
It seems that the key has been used and working from the screenshot you posted.
I would recommend deleting your config directory and restart Headset. On Linux, this is under `~/.config/Headset`. You will have to re-login afterward.
@danielravina is there a way to debug this from the user's side?

**Comment by Kandelai** [comment]
It is a new key. Every time I try and enter it in Headset, it registers as a "usage" which is why you are seeing on my google screenshot. I have already tried removing the app completely and deleted the Headset folder under the folder .config, then reinstalled it. Same error.

**Comment by danielravina** [comment]
I was able to replicate your issue (I think)
1. I restrict the key only to Youtube API
2. I regenrated a new Key
3. I clicked Save
4. I waited about a minute
5. copied the key from the same place you took the screen shot
6. Worked

@Kandelai can you try that?

**Comment by Kandelai** [comment]
I did everything you described, thanks for the detailed instructions/screenshot. Unfortunately, it did now work. I will wait a little longer and keep trying, but no go so far.

**Comment by danielravina** [comment]
I'm really sorry you are experiencing this. If you need, I can send you my working key via email. I don't mind at all

**Comment by Kandelai** [comment]
I appreciate the offer, but I will wait it out and try again down the road. It was an excellent app/service. It is unfortunate Google doesn't like to play nicely. ;-) I will check back down the road and see if it irons itself out. Best to you.

**Comment by actionless** [comment]
having the same problem

would be useful if your would be writing the real error somewhere instead of  ![2020-01-08--1578481103_400x57_scrot](https://user-images.githubusercontent.com/1655669/71973030-2df23380-320e-11ea-99b3-341f716391c0.png)
at least to stdout (if you afraid your typical user will got shocked from js stacktrace



in Google API dashboard i see what every request to `youtube.search.list ` is failed:


![2020-01-08--1578481037_3320x1846_scrot](https://user-images.githubusercontent.com/1655669/71972987-17e47300-320e-11ea-9abd-2fd8c41e015e.png)

**Comment by danielravina** [comment]
@actionless I just added a button to show the full error message. can you copy it and paste it here please?

**Comment by actionless** [comment]
![2020-01-08--1578520501_1406x2038_scrot](https://user-images.githubusercontent.com/1655669/72019491-1ba5e300-326a-11ea-8865-8d6d68df82ff.png)

**Comment by danielravina** [comment]
@actionless Sorry - I pushed another version (2.8.6) that gives more details on the error. Can you please try again? Thank you

**Comment by actionless** [comment]
finally i've got some error message in the webdev console ^^

```json
{
 "error": {
  "errors": [
   {
    "domain": "usageLimits",
    "reason": "accessNotConfigured",
    "message": "Access Not Configured. YouTube Data API has not been used in project XXXXXXXXXXXXXX before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/youtube.googleapis.com/overview?project=XXXXXXXXXXXX then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.",
    "extendedHelp": "https://console.developers.google.com/apis/api/youtube.googleapis.com/overview?project=XXXXXXXXXXXXX"
   }
  ],
  "code": 403,
  "message": "Access Not Configured. YouTube Data API has not been used in project XXXXXXXXXXXXXXXX before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/youtube.googleapis.com/overview?project=XXXXXXXXXXXXX then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry."
 }
}
```

**Comment by actionless** [comment]
So my solution to the problem was:
to create project again, for some reason adding key to existing project wasn't working

**Comment by fcastilloec** [comment]
@actionless I was about to mention that. While searching online, it seems this was the only workaround that worked.
I did manage to create a key from an existing project that did work, but this existing project is only a couple of weeks old. I've heard that old projects might have issues with inactivity, but I have no real probe about that.

**Comment by actionless** [comment]
> I've heard that old projects might have issues with inactivity, but I have no real probe about that.

yup, i've used a project from 2015

**Comment by Kandelai** [comment]
Confirmed this worked for me as well, created a new project (was using a previously created project) and API key with restrictions applied to the youtube API under it. Awesome...and thanks again.

**Comment by danielravina** [comment]
Awesome! Glad it's working :) I updated the guide and linked this issue 👍 Thanks so much!
