### ISSUE TITLE
Correct path for ubuntu desktop file

### ISSUE THREAD

**Issue by kaustubhhiware** [headsetapp/headset-electron#28]
In the missing icons for ubuntu section, the path for desktop files is actually `/usr/share/applications` or `~/.local/share/applications` as per my system [Ubuntu 16.04], and not `/usr/applications.` Please verify the correct path.

**Comment by m1guelpf** [comment]
Related: https://github.com/headsetapp/headset-electron/issues/11

**Comment by kaustubhhiware** [comment]
Also refer to @m1guelpf 's comment on #1 [here](https://github.com/headsetapp/headset-electron/issues/1#issuecomment-300068129).

**Comment by danielravina** [comment]
You are right! The path is wrong. must be a typo. I'll fix it. Thank you

**Comment by kaustubhhiware** [comment]
Closing the issue since this is fixed.
