### ISSUE TITLE
Ctrl + Shift + I Opens the developer tools even if the app is not focused

### ISSUE THREAD

**Issue by Immac** [headsetapp/headset-electron#281]
### Description

When I press `Ctrl + Shift + i` headset takes focus and opens the developer console

### Expected behaviour

If I press the aforementioned keys when headset is not focused it should not take the focus away from the app that I'm actually trying to use the keys on 

### Actual behaviour

I'm trying to inspect a variable on eclipse and headset steals the command and opens the developer console.

### Your Environment

- What OS are you using?
Windows 10 
- What version of Headset? (copy and paste from the user profile page if possible)
Core: v2.8.6, Wrapper: v3.2.0
### Screenshots

![image](https://user-images.githubusercontent.com/3265190/72099924-41bd9880-32e7-11ea-9302-0084a1bbdb2b.png)

**Comment by fcastilloec** [comment]
Thanks for pointing this out. It seems that we need to find a better way to deal with opening the developer tools. I'll take a look at what we can do to fix this and release a new version in the next days.
