### ISSUE TITLE
Headset quitting unexpectedly [Very frequent]

### ISSUE THREAD

**Issue by igauravsehrawat** [headsetapp/headset-electron#286]
### Description

I have been seeing this error message of headset quitting unexpectedly every 30 minutes of so.

### Expected behaviour

It should not quit this frequent.

### Actual behaviour

Tell us what happens instead. Provide an error message if relevant.

### Your Environment

- OSX Mojave
- Headset version: 3.2.1

### Screenshots

<img width="523" alt="Screen Shot 2020-03-10 at 15 53 08" src="https://user-images.githubusercontent.com/3696327/76325435-94b3cc00-62e7-11ea-9707-6a825e934663.png">

**Comment by fcastilloec** [comment]
Could you provide us with more info? For starters, can you post what's under "Comments" and especially "Show Details"? Also, can you post the log for Headset right after this error happens?
The logs are rewritten every time you open the app, so do not re-open Headset after you encounter the error.
You can find the logs for macOS at: `~/Library/Logs/Headset/main.log`

**Comment by igauravsehrawat** [comment]
Been working from WFH, haven't seen this message in a while.

I assume it was happening because of corporate firewall/network.
