### ISSUE TITLE
Adding a repeat and shuffle button

### ISSUE THREAD

**Issue by Parth-Vader** [headsetapp/headset-electron#29]
It would be nice to have both the buttons.

**Comment by danielravina** [comment]
It's right here man
![screen_shot_2017-06-02_at_11_13_10_pm](https://cloud.githubusercontent.com/assets/3150871/26751216/2af37124-47e9-11e7-8d80-c1d87a604107.png)

**Comment by Parth-Vader** [comment]
@danielravina Oops. Didn't see it there. Usually it with the play pause button.
Closing.
