### ISSUE TITLE
Playlist search broken/inconsistent

### ISSUE THREAD

**Issue by nv4** [headsetapp/headset-electron#291]
### Description

Some public playlists never show up in Headset search results when searching by name or ID, even though they show up in Youtube search without logging in or anything.
For example [this one](https://www.youtube.com/playlist?list=PL-qHBeApzdM4rRTVXl65KpQo9KW-Xn2ho) works but not [this one](https://www.youtube.com/playlist?list=PLY2uJAFA5RD-WubQVlxG185x1WwnQl8QT).

### Expected behaviour

Searching for playlist by name `vapor-retro-chill-etc` or ID `PLY2uJAFA5RD-WubQVlxG185x1WwnQl8QT` should show it in results.

### Actual behaviour

Literally nothing. Just indicates loading forever.

### Your Environment

Windows 10 v1909 (Build 18363.720)
latest Headset build - "Core: v2.8.7, Wrapper: v3.2.1"

### Screenshots

![image](https://user-images.githubusercontent.com/14069026/79837156-09663580-837f-11ea-85ba-7bf733843ade.png)

**Comment by fcastilloec** [comment]
Thanks for the report but after further investigation, this doesn't seem to be an issue with Headset but with Youtube API itself. For some unknown reason (it might be something with the playlist settings, who knows) some results are not returned when searching through the API even though the website does return the correct playlist.
Sorry, but it seems that this is something we can't fix.
