### ISSUE TITLE
Headset 3.2.1 stopped working (main app window is just white with no content)

### ISSUE THREAD

**Issue by gbstan** [headsetapp/headset-electron#293]
### Description

Headset 3.2.1 stopped working (main app window is just white with no content)

### Expected behaviour

Have access to the interface in the main window

### Actual behaviour

Main window is just white with no content whatsoever.

### Your Environment

- MacOS 10.15.5
- Headset version 3.2.1

### Screenshots

[Screenshot 2020-07-01 at 1 Jul 2020 - 11.10.56.pdf](https://github.com/headsetapp/headset-electron/files/4857162/Screenshot.2020-07-01.at.1.Jul.2020.-.11.10.56.pdf)

**Comment by fcastilloec** [comment]
I just tried Headset on macOS 10.15.5 and it's working without any problems. The only reason why you might get a white screen is that you're behind a proxy or firewall.
Something you can try is deleting the config files so Headset starts from scratch. You'll have to delete the directory `~/Library/Application Support/Headset`. This won't affect any of your saved playlist/collections or your liked songs. After this, Headset will start asking your for your Youtube API key.

**Comment by gbstan** [comment]
I have tried to connect without using my vpn and it then works!

Cheers.
