### ISSUE TITLE
How to use it to behind a proxy.

### ISSUE THREAD

**Issue by sameer-pandit** [headsetapp/headset-electron#3]
Seems like a good app, but how is use it behind a proxy.

**Comment by danielravina** [comment]
Can you be more specific? What's the purpose of the proxy?

**Comment by sameer-pandit** [comment]
I am behind a corporate proxy.

**Comment by danielravina** [comment]
hmmm ok is YouTube being restricted?

**Comment by sameer-pandit** [comment]
No YouTube is not restricted but all http traffic goes throw proxy. Even with http_proxy env vars set, it does not work. Does npm proxy needs to be set?

**Comment by danielravina** [comment]
ok I'm not sure then how to fix your problem. There is no need to for npm proxy though as all the packages are preinstalled with the binary. The app is makes http requests to four domains: reddit.com, github.com, amazonaws.com and googleapis.com. Hope that helps.

**Comment by kalarro** [comment]
Same issue. Youtube is not blocked, but can't install this app because of the proxy.
Other apps have a proxy configuration option where you enter your proxy credentials. No idea what they do on a technical level tho.

**Comment by sameer-pandit** [comment]
@danielravina is this issue github.com/electron#2231 helpfull ?

**Comment by kaustubhhiware** [comment]
Hey @sameer-pandit . Does entering the following commands in your terminal fix the problem ?
```
npm config set proxy http://10.3.100.207:8080   # this is just an example, http://ip:port is what you want
npm config set https-proxy http://10.3.100.207:8080
```

**Comment by hdmi** [comment]
Headset is using electron which is based in chromium and chromium does use the proxy configuration of internet explorer. So if you are using windows just type in the start menu "proxy", open the preference and add your corporate proxy to it.

Reopen headset and now it should go through the proxy.

For other operate systems the proxy should be configured with npm.

**Comment by danielravina** [comment]
I just found out you can use a proxy switch directly from electron https://github.com/electron/electron/blob/master/docs/api/chrome-command-line-switches.md#--proxy-serveraddressport
if you add this line in `index.js` your proxy should work.

```
app.commandLine.appendSwitch('proxy-bypass-list', '<local>;*.google.com;*foo.com;1.2.3.4:5678')
```

**Comment by danielravina** [comment]
Closing. issue been lingering for too long. Headset will not support proxies officially.

**Comment by asgmojtaba** [comment]
You can set environment variable for specify program by putting it before program name, so to apply HTTP(S) proxy you must launch Headset like this (in terminal):
`HTTPS_PROXY=127.0.0.1:8118 HTTP_PROXY=127.0.0.1:8118 headset`
don't forget to set both HTTPS and HTTP proxy.

You can also modify headset.desktop file (in my distro the path is /usr/share/applications/) to something like this if you don't want to run proxified-headset from terminal :

`[Desktop Entry]
Name=Headset
Comment=Discover and collect music on YouTube
GenericName=Music Player
Exec=env HTTPS_PROXY=127.0.0.1:8118 HTTP_PROXY=127.0.0.1:8118 headset %U
Icon=headset
Type=Application
StartupNotify=true
Categories=Audio;AudioVideo;Player;Music;`
