### ISSUE TITLE
App has no icon on elementary OS.

### ISSUE THREAD

**Issue by MrHuds0n** [headsetapp/headset-electron#30]
Upon installing, Headset is using the default Electron app icon.

**Comment by kaustubhhiware** [comment]
Hi @MrHuds0n !
I think you'll have to set the icon yourself. This can be achieved by editing the desktop file as described in the REAMDE [here](https://github.com/headsetapp/headset-electron#missing-icon-in-ubuntu).

**Comment by MrHuds0n** [comment]
Yeah, but I was installing it through the .deb file. A production-ready app should have its own icon.

**Comment by danielravina** [comment]
Fixed in https://github.com/headsetapp/headset-electron/pull/49. will create a release soon

**Comment by MrHuds0n** [comment]
Thank you!
