### ISSUE TITLE
Shuffle button seems to only shuffle the first 40 or so songs in a playlist

### ISSUE THREAD

**Issue by jakobkhansen** [headsetapp/headset-electron#307]
### Description

Pressing the shuffle button to start a playlist seems to only shuffle the first 40 or so songs unless you have scrolled and loaded more of the playlist beforehand. 

### Expected behaviour

Pressing the shuffle button should start the playlist with all songs shuffled, not only the first 40.

### Actual behaviour

Only the first 40/already loaded songs are shuffled. Pressing "LOAD MORE" loads new songs unshuffled as well. It is pretty tedious to load all the songs in a playlist for longer playlists.

### Your Environment

- What OS are you using?
Linux

- What version of Headset?
Core: v2.8.7, Wrapper: v3.2.1 (cloned from main branch)

Is this a problem with the Youtube API?

I could definitely try and fix this myself as I'm interested in contributing to this project.
Creating functionality to load the entire playlist at once would probably make this problem disappear, but I'm not familiar enough with the Youtube API to know if that is possible.

**Comment by fcastilloec** [comment]
We'll have to check this. I think what we could do is shuffle the next 40 songs before loading them into the player. So, if you press, "Load more" or you've reached the last song, the next ones will be shuffled.
I don't think loading all songs and then shuffling them is a good idea. There are youtube channels and playlist with thousands of videos, you'll quickly run out of API calls.

**Comment by jakobkhansen** [comment]
The problem then is that whenever you press shuffle you will always hear the same 40 songs first. Would be nice if those 40 songs were randomized from the entire playlist and not only the first 40. Is that possible or would you have to load the entire playlist for that as well?

**Comment by fcastilloec** [comment]
We'll have to take a look and see if that's possible with Youtube API, because I don't think loading the entire playlist is an option.

**Comment by danielravina** [comment]
Unfortunately,  we can't fetch a pre-shuffle playlist and we can't load the entire playlist. Youtube API is limited to max of 50 videos. https://developers.google.com/youtube/v3/docs/playlistItems/list. The reason I picked 40 initially was to save on API quota (which is not a problem so much now when users own their API key). 

The best workaround is to load as much as you can first and then shuffle, a bit of annoyance but it does what you want.

**Comment by jakobkhansen** [comment]
Alright, seems like this is a no go then. Thanks for the replies.
