### ISSUE TITLE
Disable annotations in the player

### ISSUE THREAD

**Issue by kaustubhhiware** [headsetapp/headset-electron#31]
When I clicked on a random suggestion in the Headset-player, headset opens up another window playing that video, and not through the default console. 
Additionally, clicking on another annotation in the new window creates an altogether new window. [At this point, there are 4 headset windows, 2 default ,2 extra]
Is it possible to disable annotations in the video being played, or better yet, play that video via headset.

Attaching an image as example. [Pardon my horrific image editing skills]
![imageedit_5_8740708902](https://user-images.githubusercontent.com/11318551/26928683-a422a4a4-4c74-11e7-8fbc-339e6ce18bbd.gif)

**Comment by danielravina** [comment]
One of the api requirements is 

> You and your API Clients must not, and must not encourage, enable, or require others to: modify, interfere with, replace, or otherwise disable any functionality, data, or content made available as part of, or in connection with, YouTube API Services. For example, you must not remove, obscure, alter, or disable any links that appear in YouTube players or in API Data.

I can't control what goes beyond or during the click. The best I can do is not advertise it as a feature.

**Comment by kaustubhhiware** [comment]
Closing the issue to avoid API violations clashes.
