### ISSUE TITLE
Media keys not available for MacOS?

### ISSUE THREAD

**Issue by greeneryAO** [headsetapp/headset-electron#317]
The faq says there are, maybe it's just my system but I don't think so because youtube and youtube music media control work for me as expected.

All I can do in headset is inch forward or back by about 3 seconds at a time using my arrow keys left or right.

If they don't exist, I would really appreciate keyboard shortcuts for next, prev, copy link to clipboard, like song, and 15 sec skips so I can control this great player while it's minimized.

**Comment by fcastilloec** [comment]
There is media key support but only for `play/pause`. `previous` and `next`. When Headset starts it should ask you for permission to enable media-keys support, see https://github.com/headsetapp/headset-electron/issues/206#issuecomment-435954900
If you're encountering any issues, please let me know.

**Comment by greeneryAO** [comment]
I think it might be my system specific unfortunately, my media keys F7, F8, F9, might be dead or they might be getting overridden by something, I have to play around in other programs and see if they work, even play, next and prev would be good enough. I'll try re-granting permission.

**Comment by fcastilloec** [comment]
Let me know how it goes. I'd also be interested to see if your system is case sensitive or not. There might be a bigger bug with electron itself.

**Comment by greeneryAO** [comment]
jumped the gun on that, it was my system, something was causing those keys to not work but i booted into safe mode, then it worked (slowly), then let it do its work and now it works in main account so all good.

**Comment by igauravsehrawat** [comment]
It works only when screen is unlocked.

On lock screen, I can't pause music from headset. Anyone else facing same issue?

Thanks
