### ISSUE TITLE
Deleting likes collection leads to empty page

### ISSUE THREAD

**Issue by kaustubhhiware** [headsetapp/headset-electron#32]
I accidentally deleted the likes collection by clicking on delete button on the likes tab. Due to this, I get an empty tab in likes now, and I'm not able to like any video now. Sign out / log out options are not available either.
The only resolution seemed to be complete removal, and then installation via the deb. [I had originally installed via the deb]

**Comment by danielravina** [comment]
So sorry about it, this is a bug, the likes are not supposed to be removed. I just pushed a fix that prevents you from deleting it.
