### ISSUE TITLE
Mouse back button makes player controls disappear

### ISSUE THREAD

**Issue by 3Nex** [headsetapp/headset-electron#325]
### Description

Clicking the back button on the mouse (one of the extra buttons on the side of the mouse).

### Expected behaviour

Either nothing, or maybe going back in the in-app navigation.

### Actual behaviour

The app looks like it's initializing from scratch again, but without the song stopping.

The splash screen with the loading animation appears for a second, then the app loads in again, however it shows without the player controls on the bottom, and no way to see the song queue; despite the song never stopping throughout.

The controls can easily be brought back by just clicking another song, which will cause the selected to play and display the player controls and song queue again, but it interrupts the previous song/queue.

### Your Environment

- What OS are you using? Xubuntu 20.04
- What version of Headset? Core: v2.8.8, Wrapper: v3.2.1

### Screenshots

🖼

**Comment by fcastilloec** [comment]
Thanks, I can reproduce this on my Ubuntu machine. When pressing the button, you go back to the previous view. So if you were in Search and then go to Account, press the button and you'll be back at Search. If you haven't switch views then pressing the button will do nothing.

I'll take a look if disabling those keys might be a good idea and feasible. It's usually not a good idea to disable those keys. Let me see what I can do.

If you have a second machine/installations with Windows and/or macOS, have you experience the same behavior there?

**Comment by 3Nex** [comment]
No, sorry, i have no other OS..

**Comment by fcastilloec** [comment]
It seems this won't be able to be fixed. I haven't found any way to disable mouse buttons. A newer version of electron has fixed the disappearing player and be available once we release the new version.
I don't know how long it'll take to release the new version, we're waiting on getting our signing certificate renewed but it's taking a lot longer than expected.

**Comment by fcastilloec** [comment]
With the release of the new version, the mouse back button is working as expected and the player no longer disappears.
