### ISSUE TITLE
How do I open the app?

### ISSUE THREAD

**Issue by Amolith** [headsetapp/headset-electron#33]
This is an incredibly stupid question, I know. However, I've been using Ubuntu for about a week. I switched from ChromeOS so this is all a HUGE change and I have no idea what I'm doing. I installed the app using dpkg -i then apt-get -f. I just can't figure out how to open it.

**Comment by m1guelpf** [comment]
If you did that, you should be able tu run 'headset' to open it, or you can search for it.

**Comment by danielravina** [comment]
@Amolith is this still an issue?

**Comment by Martina-Neumayer** [comment]
Well.. Under Linux Mint Mate the app lands after the installation under the "Programs -> Accessories" instead of "Programs -> Sound and picture". I mean in the Mint Menu.

**Comment by danielravina** [comment]
You can run `headset` after installing https://github.com/headsetapp/headset-electron/releases/tag/v1.6.1
