### ISSUE TITLE
Can't see Discord Rich Presence even when option is enabled.

### ISSUE THREAD

**Issue by saieeshb** [headsetapp/headset-electron#330]
### Description

I'm unable to see the discord rich presence even though I have the option turned on in the app itself.

### Expected behaviour

Discord should show the Rich Presenc from Headset

### Actual behaviour

Nothing shows up instead.

### Your Environment

- What OS are you using?
  Ubuntu 18.04 
- What version of Headset? (copy and paste from the user profile page if possible)
  Core: v2.8.8, Wrapper: v3.2.1

🖼

**Comment by fcastilloec** [comment]
Hi @FlaminGummy 
Discord is not currently working because we released a new `core` version and we haven't been able to release a new `wrapper` version due to some delays in getting the signing certificate for Windows.
We actually just received the new certificate and in the next few days, we'll be releasing a new version that will have Discord support.

In the meantime, it would be greatly appreciated if you can test Discord by using the latest code in the `main` branch. If you're not too familiar with git and npm, here's some commands that can get you running:

``` bash
git clone https://github.com/headsetapp/headset-electron.git
cd headset-electron
npm ci
npm run headset
```

**Comment by FlaminGummy** [comment]
Hello! Thank you for the response! I did as you said and it works now! Thanks! I'll be looking forward to the release! :D

**Comment by fcastilloec** [comment]
We just released a new version yesterday, so you can switch back to installing Headset however you prefer.

**Comment by FlaminGummy** [comment]
I see! Thank you for the info!

**Comment by FlaminGummy** [comment]
Hey! It looks like it shows the first song played and then gets stuck on 00:00 on that song but doesn't show when i move to different song.

**Comment by fcastilloec** [comment]
@FlaminGummy I just tested it on Ubuntu 20.04 and everything is working as expected. I'll test it on my virtual machine for 18.04.
BTW, How did you install the app?

**Comment by FlaminGummy** [comment]
I used the .deb file

**Comment by fcastilloec** [comment]
@FlaminGummy sorry for the late response, I've been busy.
I tried with Ubuntu 18.04 and other distros based on this version: Mint, Elementary, and Pop! OS. Everything is working as expected.
The only thing I can think of is if you updated your Headset (using the .deb file), that updates the wrapper, the core is loaded directly from the internet and you might have some files cached showing an older version. By now, it should have been updated and if this was the problem you shouldn't experience it anymore. Just to be safe, you can delete all cache files by deleting `~/.config/Headset`. You'll have to re-input your API key, and re-login.

Here's a video showing it working under Ubuntu 18.04:
https://user-images.githubusercontent.com/1280530/106230362-2d736480-61a4-11eb-97f2-8abbcc2783a3.mp4
