### ISSUE TITLE
Debian package error

### ISSUE THREAD

**Issue by lfom** [headsetapp/headset-electron#356]
### Description

Current .deb package (v3.3.2) as well as instructions about how to add the repo and install in README are broken.

### Expected behavior

Install Headset without errors, as well as properly add the repo for future updates as instructed in README.

### Actual behavior

The available -deb file in Releases can be used to install Headset, but the installation results in an error, that cannot be fixed unless Headset is uninstalled:

```
$ sudo apt install ./headset_3.3.2_amd64.deb      
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'headset' instead of './headset_3.3.2_amd64.deb'
Suggested packages:
  gir1.2-gnomekeyring-1.0 libgnome-keyring0
The following NEW packages will be installed:
  headset
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
After this operation, 235 MB of additional disk space will be used.
Get:1 /home/lfom/Downloads/headset_3.3.2_amd64.deb headset amd64 3.3.2 [78,3 MB]
Selecting previously unselected package headset.
(Reading database ... 492361 files and directories currently installed.)
Preparing to unpack .../headset_3.3.2_amd64.deb ...
Unpacking headset (3.3.2) ...
Setting up headset (3.3.2) ...
dpkg: error processing package headset (--configure):
 installed headset package post-installation script subprocess returned error ex
it status 1
Processing triggers for desktop-file-utils (0.24-1ubuntu3) ...
Processing triggers for mime-support (3.64ubuntu1) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Processing triggers for gnome-menus (3.36.0-1ubuntu1) ...
Processing triggers for bamfdaemon (0.5.3+18.04.20180207.2-0ubuntu2) ...
Rebuilding /usr/share/applications/bamf-2.index...
Errors were encountered while processing:
 headset
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

The app is installed, and taking a loot as the post install script, it seems that is related to an error adding the repository for future updates.

Similarly, the instructions about adding the repository manually is not complete:

`wget -q http://headsetapp.co/headset-electron/headset.asc -O- | sudo apt-key add -  `

it should be (missing part is **--keyring /etc/apt/trusted.gpg.d/headset.gpg**):

`wget -q http://headsetapp.co/headset-electron/headset.asc -O- | sudo apt-key --keyring /etc/apt/trusted.gpg.d/headset.gpg add -  `

But even after adding the source correctly, installation results in the same error as the manual installation of the deb package, because probably it is the same file after all.

### Your Environment

- What OS are you using? Pop!_OS 20.04 (like Ubuntu 20.04)
- What version of Headset? v3.3.2

### Screenshots

N/A

**Comment by fcastilloec** [comment]
I've tested this on Ubuntu 20.04, Fedora 33, Linux Mint 20.1, and Ubuntu 18.04 and haven't had any problems installing with the `.deb` or adding the repository using the exact instructions listed on the README.

I'm going to try installing Pop!_OS on a virtual machine and see what's going on. If I'm not mistaken, I read somewhere that `apt-key add` is deprecated on newer Ubuntu versions. I'll have to check what's changed and update the instructions and the `.deb`.
The problem is that the `.deb` post-installation script does exactly the same as the README instructions.

Thanks for reporting this!

**Comment by lfom** [comment]
Just a follow up: I edited the post-installation script with the changes I suggested, and it was installed without errors. And it is the command I usually see online anywhere where there are instructions about how to add the key manually, for instance:
https://brave.com/linux/#linux

**Comment by lfom** [comment]
I think I have figured out what was causing the error: so I had another repository that had a colon (_":"_) in its file name, and this was causing errors when using `apt-key` commands to add or delete keys without specifying the file name directly. That's why it does not cause an error after a fresh installation or if all the files in **/etc/apt/trusted.gpg.d** are properly named.
Anyway, the man page for `apt-key` has a note about _add_ that it should specify a file name directly, as well as a meaningful name should be used. If it is not, then the key is added to **/etc/apt/trusted.gpg** file, and can only be accessed via `apt-key` commands.
If you do not want to rely on `apt-key`, then you can use `gpg` and `dd` the key to the proper file, but its more complicated, so in my opinion it is simpler and safer to just specify the file destination when using `apt-key`.
Please feel free to close this issue after you read this message.
Regards

**Comment by fcastilloec** [comment]
Thanks but it's not as simple as that. Putting a key on `/etc/apt/trusted.gpg` doesn't address the issue of why `apt-key add` is deprecated.
I'm currently busy with my regular job but I'll be implementing the proper way to fix this so we don't put any keys on `trusted.gpg`

**Comment by fcastilloec** [comment]
We've released a new version with fixes for this. We've also updated the README to reflect the new way we should install the repository.
@lfom could you please test out the README instructions and/or the `.deb` file in the releases? Also, the new package deletes the old key installed with `apt-key add` and moves everybody to the new method. In your specific case (and anybody else that installed the key with `apt-key --keyring /etc/apt/trusted.gpg.d/headset.gpg`) you'll have to manually delete that key, the new `.deb` package doesn't touch that.
And for anybody else that stumbles upon this issue. The packages are supported for Ubuntu 18.04+, we don't test for older versions.

**Comment by lfom** [comment]
I am sorry for the late reply. I just did a clean install of headset_3.3.3_amd64.deb on a machine with Pop!_OS 20.10 that never had Headset app installed and it worked fine, I checked out and the repository was also added for future updates, no errors.
