### ISSUE TITLE
Music loop

### ISSUE THREAD

**Issue by R3J3CT3D** [headsetapp/headset-electron#36]
Hello, I encountered a problem.

When I play a music, it starts for about 1-2 seconds and returns to the beginning.
I tried on Linux and on MacOS, same result.

**Comment by danielravina** [comment]
This was reported and fixed couple of days ago. if you change this line https://github.com/headsetapp/headset-electron/blob/master/index.js#L89 to `!isDev` you will get the developer console. can you see if you get any errors?
in mac, the file is located in `/Applications/Headset.app/Contents/Resources/app/index.js`

Thanks

**Comment by R3J3CT3D** [comment]
Thank you for this quick return!
I do 't have access to my mac, can I change this line from linux?

**Comment by danielravina** [comment]
yes. in linux, the file is at `/usr/lib/Headset/resources/app/`

**Comment by R3J3CT3D** [comment]
Oh .. The problem is gone ..
I don't know why but the music don't come back at the beginning, with or without the developer mode

**Comment by danielravina** [comment]
ok cool. I guess you didn't have the latest version (with the fix). the update happens when you open the app.
