### ISSUE TITLE
Share youtube link

### ISSUE THREAD

**Issue by MartinMuzatko** [headsetapp/headset-electron#37]
Hello!
Right now, if I want to share a video with someone else I need to open the video player and rightclick the video - copy share Url.

However, It would be great as an addition to the actions menu (...) to share the video. I guess you could use [clipboardjs](https://clipboardjs.com/) for that.

**Comment by danielravina** [comment]
I actually try to implement it in the very first version of headset and had some issues with clipboardjs. I can't remember now what it was, but I will give this another shot. This is a very useful feature. Thanks for your feedback!

**Comment by danielravina** [comment]
Hey! Sharing link added:
<img width="250" alt="screen shot 2017-11-13 at 8 01 09 pm" src="https://user-images.githubusercontent.com/3150871/32762313-939f393e-c8ad-11e7-89f3-5a3e0bb52d8e.png">
