### ISSUE TITLE
Support log-in in multi machines.

### ISSUE THREAD

**Issue by nhtua** [headsetapp/headset-electron#38]
I use Headset on both my laptop and a company PC. When I login my account on the company PC then Laptop's Headset will be logged out. Can Headset login my accounts in multi machines?

**Comment by danielravina** [comment]
I actually have the same issue and I understand you completely! I was tolerating this and pushing it off until someone will request that. I guess that time has come and now it's on my todo list :) thanks for the request!

**Comment by SJTUboy** [comment]
I have the same issue!

**Comment by danielravina** [comment]
I made the necessary changes to the API and database to allow login to multiple machines. Please let me know if you experiencing any issues before I close this issue. Thanks!

**Comment by Pepello** [comment]
Hi, I'm logged in Headset from two pc, but I can use it only on the last pc I've logged in succesfully. On the other pc the app is stuck on initial loading. 
![image](https://user-images.githubusercontent.com/15652360/32142789-64645b88-bc9e-11e7-9f9a-69c23df08f32.png)

**Comment by danielravina** [comment]
@Pepello can you send me your email to hello@headsetapp.co so I can troubleshoot?
You can also talk to me on slack with this link: https://tinyurl.com/y7m8y5x4

Thanks!

**Comment by Pepello** [comment]
@danielravina Your fix seems to work. Thank you very much!

**Comment by SJTUboy** [comment]
![image](https://user-images.githubusercontent.com/13373715/32204942-66922400-be27-11e7-9a66-29b08d60d8fe.png)

**Comment by danielravina** [comment]
Emailed you back

**Comment by SJTUboy** [comment]
Thank you very much! It't caused by the Great Firewall in China.
When I use VPN, it's OK
![image](https://user-images.githubusercontent.com/13373715/32377317-30771476-c0e2-11e7-8053-343ee97c2d92.png)
I love Headset app very much! Thanks again

**Comment by danielravina** [comment]
Thanks everyone who contributed and reported! I will close this issue now.

**Comment by danielravina** [comment]
@SJTUboy bytheway, that weird white margin on the right-bottom is fixed. `v1.6.1` had an outdated package for Windows. I updated the fix and it's available here https://github.com/headsetapp/headset-electron/releases/download/v1.6.1/HeadsetSetup.exe

**Comment by SJTUboy** [comment]
Thanks!

I will update now!
