### ISSUE TITLE
Saving window position between app runs

### ISSUE THREAD

**Issue by miniscruff** [headsetapp/headset-electron#39]
I have a very specific window position setup between my work ( unity / visual studio ), chrome and discord. Headset fits perfectly in this nice little spot, unfortunately its hard to fit it in that one pixel position and having to do it every morning is tedious. It is not a very big problem but if it is easy to add I know it would help quite a bit personally.

If you need repro steps:
1. Open the app
1. Move the app somewhere other than where it started
1. Close the app
1. Reopen the app

Ideally the app would be where I placed it before I closed it.

**Comment by danielravina** [comment]
No plans to add this feature but I can show you how you can set it up on you machine if you want!

**Comment by miniscruff** [comment]
Oh, sure yea i guess that should work.

**Comment by miniscruff** [comment]
Oh I am on windows, I have done some node programming although I mainly do c# and python. I do have two monitors and would like it placed on the second one if that matters.

**Comment by danielravina** [comment]
1 .Navigate to the folder where the app is installed: (using the command line)
`C:\Users/[USER]\AppData\Local\Headset\app-1.5.4\resources\app`
2. run `npm install --save electron-window-state`
3. Open the app `index.js` and change 
```js
// top
const windowStateKeeper = require('electron-window-state');
...

const start = () => {
  let mainWindowState = windowStateKeeper() // <-- Add this
  console.log(mainWindowState.x, mainWindowState.y);
  win = new BrowserWindow({
    x: mainWindowState.x, // <-- And this
    y: mainWindowState.y, // <-- And this
    ...
  });
  mainWindowState.manage(win); // <-- And this
  ...
```
That should fix your problem. I might add that to the next release.

**Comment by miniscruff** [comment]
Awesome! Worked like a charm, thank you so much. If it would help I can add the change to a pull request.

**Comment by danielravina** [comment]
Sure!

**Comment by miniscruff** [comment]
Alright, will do that now.
