### ISSUE TITLE
Current queue

### ISSUE THREAD

**Issue by umpirsky** [headsetapp/headset-electron#4]
It would be nice if possible to add any song to current queue, to play after current song.

**Comment by danielravina** [comment]
Ha! Just released a re-ordering feature for the queue and collections. Check it out. That was a pre-requisite for that ☝️. adding/removing songs is next step.

**Comment by umpirsky** [comment]
But looks like all songs from search are automatically added to current queue?

**Comment by danielravina** [comment]
If you play a song from search, the queue is populated with a list of related songs to what you picked. What  I'll do is add an option for a "Play next" or "Add to queue". in the Queue itself, you'll be able to remove songs individually. does it make sense?

**Comment by umpirsky** [comment]
@danielravina "Play next" is good, but here is scenario that is most common for me:

1. Search for artist (e.g. Pink Floyd)
1. Click one of top results and play it.
1. While it;s playing add more songs to the queue.

I expect to get enqueued songs played next.

**Comment by danielravina** [comment]
Cool. That's exactly what the "Play Next" will do. What I want to avoid is clicking on one of the search results and only have one track in the queue if users don't manually add songs. This should be a play it and forget it kind of experience.

**Comment by umpirsky** [comment]
So, if I do:

1. Play Next - Song A.
1. Play Next - Song B.
1. Play Next - Song C.

Play order will be C, B, A, right?

**Comment by danielravina** [comment]
Looks right to me.

**Comment by umpirsky** [comment]
OK, that would work. :)

**Comment by danielravina** [comment]
Hi @umpirsky your feature request is now live!

![jun-30-2017 23-25-31](https://user-images.githubusercontent.com/3150871/27759685-7fc2d178-5deb-11e7-9931-19b8eaaa73ef.gif)

**Comment by umpirsky** [comment]
@danielravina Neat, thanks! `v1.5.4-deb`? I'll try it out soon!
