### ISSUE TITLE
Javascript Error on Windows 10

### ISSUE THREAD

**Issue by kelmouloudi** [headsetapp/headset-electron#403]
When I start the app, I get this long error (the app used to work just fine) :

https://i.imgur.com/352Aeli.png

I uninstalled the app then reinstalled it but the error stays the same.

I run Windows 10 Pro, Version 21H1, OS build 19043.1110. Experience: Windows Feature Experience Pack 120.2212.3530.0.

Thanks.

**Comment by fcastilloec** [comment]
Duplicate of #395
