### ISSUE TITLE
Allow search YouTube users and playlists

### ISSUE THREAD

**Issue by lardissone** [headsetapp/headset-electron#41]
It would be great to add users/playlists as collections. But at the moment I think there's no way.

**Comment by danielravina** [comment]
Great suggestion. I'll investigate how this could be integrated with the API

**Comment by danielravina** [comment]
Actually, it's quite simple. Coming soon!
![screen shot 2017-07-24 at 11 11 29 pm](https://user-images.githubusercontent.com/3150871/28558175-8ae1d27e-70c5-11e7-8d53-2bd40c2ac5b8.png)

**Comment by lardissone** [comment]
@danielravina awesome! And also is possible to see that user playlists? For example see this account: https://www.youtube.com/channel/UCEkBEbI7ME92qqjMjqvuIQA

This user has several playlists sorting videos by genre, like: Space Music, Psychedelic Trance, etc.

It would be great to be able to follow just a playlist.

**Comment by danielravina** [comment]
The feature is now live (only uploads though). I will add the channel-playlists option in the next iteration!

**Comment by lardissone** [comment]
Awesome! Loving it.

**Comment by danielravina** [comment]
Opened a new issue #86 with the enhancement of this issue.
