### ISSUE TITLE
macOS is unable to identify developer

### ISSUE THREAD

**Issue by dhruv-agg** [headsetapp/headset-electron#411]
### Description

macOS is unable to identify developer

### Expected behaviour

developer info should be specified

### Actual behaviour

macOS is unable to identify developer

### Your Environment

- What OS are you using: MacOS BigSur11.5
- What version of Headset? (copy and paste from the user profile page if possible) : 3.3.3 (downloaded via "brew install --cask headset" & also via .dmg file)

### Screenshots

🖼

**Comment by danielravina** [comment]
Sorry for the inconvenience. I didn't pay Apple membership yet. it is still possible to open the app without the developer being identified.

**Comment by fcastilloec** [comment]
@dhruv-agg we've released [v4.1.0](https://github.com/headsetapp/headset-electron/releases/tag/v4.1.0) which has a signed app for macOS
