### ISSUE TITLE
Flatpak warning: Freedesktop SDK 19.08 runtime EOL

### ISSUE THREAD

**Issue by IzNoGud78** [headsetapp/headset-electron#412]
Every time I'm looking for updates with flatpak I receive the following message:

```
Info: org.freedesktop.Platform//19.08 is end-of-life, with reason:
   The Freedesktop SDK 19.08 runtime is no longer supported as of September 1, 2021. Please ask your application developer to migrate to a supported version
Applications using this runtime:
   co.headsetapp.headset
Info: org.freedesktop.Platform.VAAPI.Intel//19.08 is end-of-life, with reason:
   The Freedesktop SDK 19.08 runtime is no longer supported as of September 1, 2021. Please ask your application developer to migrate to a supported version
Info: org.freedesktop.Platform.GL.default//19.08 is end-of-life, with reason:
   The Freedesktop SDK 19.08 runtime is no longer supported as of September 1, 2021. Please ask your application developer to migrate to a supported version
```

Even if, despite this warning, the program seems to continue to work normally without any kind of problem.

**Comment by fcastilloec** [comment]
Thanks for reporting this. I'll make sure to update the flatpak to fix this warning

**Comment by fcastilloec** [comment]
I've updated the flatpak, I tested it and the newer runtime was downloaded. I'm not sure if people we'll get an update since technically Headset didn't change versions.
If you don't see an update for Headset of flathub, I would recommend uninstalling it and reinstalling it.
