### ISSUE TITLE
conflict with Youtube video played in web browser (sound output)

### ISSUE THREAD

**Issue by xididri** [headsetapp/headset-electron#419]
### Description

When Headset is playing music from Youtube, if I play a Youtube video in a web browser, clicking play/pause on the video also play/pause Headset sound output (despite play status still showing playing on Headset). Once yYoutube video (in web browser) is finished, there is no sound output on Headset.

### Expected behaviour

Headset sound output should not be impacted by Youtube videos played in web browser.

### Actual behaviour

Headset sound output is controlled by Youtube video in browser.

### Your Environment

- Windows 10 20H2, Firefox 93.0
- Headset Core: v2.11.0, Wrapper: v3.3.3

**Comment by fcastilloec** [comment]
I've never seen this happen, and it's even weirder because Headset is based on electron which is based on Chromium, so I would have suspected that Headset shared some configs with Chrome but not Firefox.
I'm currently on holiday, so it's going to take me a long time before I can run some tests and see what's going on.

**Comment by fcastilloec** [comment]
Sorry for taking so long. I've looked into this and I haven't been able to reproduce this at all. I'm using the latest Firefox (v95.0.2) and Windows 10 21H2. I've tried different videos, playing the same video on both places, but nothing.
The only thing I can think of might be some extension making things weird. Another thing might be your audio drivers, there might be something weird that only one sound is allowed to play at a time. If you have another app that plays sounds (vlc, Spotify, etc) try playing something there and also on Youtube in Firefox and see if you experience the same behavior.

I'm pretty sure this is specific to your own computer and configuration, and not related to Headset. I recommend testing your problem on another computer and seeing if you can reproduce it there. If you can reproduce it, feel free to paste the steps and details so I can take a look.

**Comment by xididri** [comment]
Thank you for the time you took to look at this, indeed this might be related to the audio drivers or how windows pauses a "music" app when another one is playing, I don't really understand but I have investigated further and it happens in a very specific configuration where I have multiple sound output playing at the same time (bluetooth headset and bluetooth speakers).

- web browser (tried chrome and firefox) => output to bluetooth headset (Sony WH-1000XM)
- headset app => output to bluetooth speakers

This is controlled in Windows Settings > System > Audio > App volume and device preferences

The weird thing is when I play/pause music in another website (not youtube) this does not affect headset but when I play/pause a video on youtube it does

Anyway I will close this issue because whatever it is I don't think this is something you can fix in code. Thank you again for checking!
