### ISSUE TITLE
Problems with Arch Linux

### ISSUE THREAD

**Issue by koenigsreiter** [headsetapp/headset-electron#44]
Hello!

I've tried to install the apps based on the install instructions in the readme and everything worked fine (I omited the last step). I can even start the app, but as soon as I try to play music the Interface freezes completely. The music is still  playing for a few seconds, but there is no interaction with the program possible anymore.
Is there some kind of log where I can find some info which might help you, or do you need more information? I'd love to help if that's somehow possible.

![image](https://user-images.githubusercontent.com/17050750/28386669-9020c9b8-6ccc-11e7-8b6c-e252e8539641.png)
That's how it usually freezes and only a force quit can close the program.

Have a nice day!

**Comment by danielravina** [comment]
you can turn on developer tools by changing this line https://github.com/headsetapp/headset-electron/blob/master-linux/index.js#L98 to `if(!isDev)` Other than that there is no other log. If you see any errors, please post them here. Thanks!

**Comment by koenigsreiter** [comment]
Unfortunately it doesn't show anything so I guess it's just because there is something wrong with my PC :/
But thanks for your help!

**Comment by danielravina** [comment]
=\ sorry to hear that. I'll close it off for now. If you try it on a new PC and you still have the same issue, feel free to re-open or create a new issue.
