### ISSUE TITLE
Headset Snap not launching

### ISSUE THREAD

**Issue by soumyatheman** [headsetapp/headset-electron#453]
### Description
I use Ubuntu 21.10 and the snap version of Headset. Whenever I launch the app it doesn't start.

### Expected behaviour

It should have started normally and we should have given the options and songs and all.

### Actual behaviour

It doesn't start and gives an error in terminal.
`(headset:35275): Gtk-WARNING **: 14:37:13.804: cannot open display: :0`

### Your Environment

- What OS are you using? 
- Ubuntu 20.10
- What version of Headset? 
- 3.3.3 (snap installed from ubuntu software center)

### Screenshots
![image](https://user-images.githubusercontent.com/72045785/152380305-30bb327b-8c84-46fc-920d-3d2f009f7eca.png)

🖼

**Comment by fcastilloec** [comment]
Let me check if I can reproduce this. I'm a little busy this week so I apologize in advance if I don't get back to you this week

**Comment by soumyatheman** [comment]
> Let me check if I can reproduce this. I'm a little busy this week so I apologize in advance if I don't get back to you this week.
> 
> FYI, this version of Ubuntu is not supported anymore, so I highly recommend switching to a supported version like `20.04` or `21.10`.

I'm very sorry for my mistake. I use Ubuntu 21.10. Actually after a lot of time I'm returning to Ubuntu from Arch. However, the deb package is working fine. If you could add it in a ppa or something like that so that it can be installed from software center.

**Comment by fcastilloec** [comment]
If you installed the `deb`, it automatically adds the Headset repo to your system and keeps it updated, no need to do anything. We host our repo here in Github, not with Launchpad (a.k.a PPA).
I don't think we explicitly mention that on the README, maybe we should. There's definitely instruction on the README on how to manually add the repository to your system for Ubuntu and Fedora based systems.

Using Ubuntu 21.10 will make it easier for me to test.

**Comment by soumyatheman** [comment]
> If you installed the `deb`, it automatically adds the Headset repo to your system and keeps it updated, no need to do anything. We host our repo here in Github, not with Launchpad (a.k.a PPA). Most apps out there automatically add a repository to your system when you install their `deb` (i.e. Skype, Slack, Google Chrome, etc). I don't think we explicitly mention that on the README, maybe we should. There's definitely instruction on the README on how to manually add the repository to your system for Ubuntu and Fedora based systems.
> 
> Using Ubuntu 21.10 will make it easier for me to test.

Well, I truly prefer sandboxed apps than the good old packages. So, I'd always prefer the snap one.

**Comment by fcastilloec** [comment]
So, after you told me the error was with Ubuntu 21.10 I had a hunch of what was going on, and indeed, I was correct.

This is not a bug on Headset but rather Ubuntu and Wayland and how they interact with snaps (see [here](https://forum.snapcraft.io/t/apps-wont-run-and-crash-on-gnome-wayland/20322)). I'm pretty sure that other snaps are also having this problem.

Luckily, there is a workaround, you can start Headset (or any other snap that's having issues) with `env DISABLE_WAYLAND=1 headset` (or replace `headset` for any other snap).

You could also edit `/var/lib/snapd/desktop/applications/headset_headset.desktop` and add the workaround to the `Exec=` line. It will look something like this:

```
Exec=env DISABLE_WAYLAND=1 env BAMF_DESKTOP_FILE_HINT=/var/lib/snapd/desktop/applications/headset_headset.desktop /snap/bin/headset --no-sandbox %U
```
That way you can start Headset from the application menu/icon, but you'll still have to do the workaround every time you start it from the command line, and any time there's an update, you'll have to modify the desktop file again.
