### ISSUE TITLE
Headset Linux desktop file doesn't contain keywords

### ISSUE THREAD

**Issue by fcastilloec** [headsetapp/headset-electron#46]
I think it's a good idea to include keywords in the .desktop file so users can easily find the application. Currently, on Ubuntu, you have to type Headset, with the proper case (H capital, followed by lower) in order to find the app.
If the 'Headset.desktop' file could include:

Keywords=headset;music;player

The users can type headset without the first letter being capital, and also it will show if the user is searching for music or a player.

**Comment by danielravina** [comment]
I like this suggestion. It will be great if the repo will have a .desktop file in the root folder so users can use instead of copying from the readme. Do you mind opening a PR against the master-linux branch?

**Comment by fcastilloec** [comment]
Sure, I can create the PR. I'll do it over the weekend.

**Comment by danielravina** [comment]
fixed in https://github.com/headsetapp/headset-electron/pull/49
