### ISSUE TITLE
High CPU usage when internet is disconnected

### ISSUE THREAD

**Issue by igauravsehrawat** [headsetapp/headset-electron#467]
### Description

First of all, thanks for the awesome app. Bought a subscription already.
When headset is running and if there internet is disconnected. Let's say you move to different room or you switch off wifi.

Then you will get below popup and one core of CPU is full 99% usage.
<img width="888" alt="Screen Shot 2022-04-17 at 12 35 43" src="https://user-images.githubusercontent.com/3696327/163710971-f5089fd6-1497-4345-90a7-93d83ffad990.png">
I suspect the Javascript process is running in infinite loop. 
And it is not even trying to reconnect after internet is back.

### Expected behaviour
The application should not run in while(kinda)/infinite loop.

There should be delay and it should try to reconnect to internet.

### Actual behaviour

Process goes Brrrrrr, infinite loop and not trying to reconnect.
Laptop fan feels like a jet ready for take-off 🛫🛫 

### Your Environment

- What OS are you using?
  -  MacOS Big Sur
- What version of Headset? (copy and paste from the user profile page if possible)
  - 3.3.3 (Lucky 3)

### Screenshots

🖼
<img width="888" alt="Screen Shot 2022-04-17 at 12 35 43" src="https://user-images.githubusercontent.com/3696327/163711080-a99a78ea-dc80-4aef-9401-e0cde39976c8.png">

**Comment by fcastilloec** [comment]
I'm pretty sure the CPU usage is an issue with electron itself and not our app. We never really thought about not having network access, since our app requires it to work. We could handle network disconnects better. We're in the process of finalizing a new release, which updates electron and might fix the CPU issue, and maybe we could add something that handles network disconnects, but I can't promise it'll be included in the next release.

**Comment by igauravsehrawat** [comment]
@fcastilloec Many thanks for acknowledging and considering above issue.

Looking forward to new release.

**Comment by fcastilloec** [comment]
The new version of Headset should have fixed the memory issue. We'll be releasing another version soon that will do a soft check for connectivity only when starting

**Comment by igauravsehrawat** [comment]
That's great.

Can we add some delay in exception handling/error handling, I believe it keeps on trying again and again if there is an exception during to failed internet.

**Comment by fcastilloec** [comment]
@igauravsehrawat there's a new version released that includes a check when opening the app for network connectivity. If the network goes away while the app is running, that won't be handled, yet... We might release a new version of the `core` with some checks for network connectivity.
The high CPU usage might have been a bug with electron, and with the new version, this might not be the current behavior. I'm closing this issue but feel free to comment/re-open if you still have problems.
