### ISSUE TITLE
Missing code signature in MacOS version 4.0.0

### ISSUE THREAD

**Issue by suschizu** [headsetapp/headset-electron#478]
version 3.3.3 was signed with Daniel Ravina (4BJNEK4V69) 

but version 4.0.0 isn't signed at all: 

```
codesign -dv --verbose=4 /Users/work/Desktop/Headset.app 
/Users/work/Desktop/Headset.app: code object is not signed at all
```

download: https://github.com/headsetapp/headset-electron/releases/download/v4.0.0/Headset-4.0.0.dmg

can you verify that the code signature is missing now? 
thanks

**Comment by fcastilloec** [comment]
Yes, unfortunately, we had to stop paying for signing certificates; they were prohibitively expensive.
We haven't ruled out signing future releases, we are actually considering having a new minor release signed only for macOS but not Windows

**Comment by suschizu** [comment]
ok - sorry to hear! but thanks for the quick answer
