### ISSUE TITLE
Crash when Discord Rich Presence enabled - "details is not allowed to be empty"

### ISSUE THREAD

**Issue by minimar** [headsetapp/headset-electron#483]
### Description

With Discord rich presence enabled in the settings, most songs crash the app upon attempting to load them.

### Expected behaviour

The song loads normally and displays the rich presence correctly without crashing the app.

### Actual behaviour

App immediately crashes.

### Your Environment

- Windows 10 21H2 19044.1706
- Core: v2.11.0, Wrapper: v4.1.0

### Screenshots

![KWLn21Gk2E](https://user-images.githubusercontent.com/29131418/169607922-6d621d81-90c2-458a-960e-56654d8db327.gif)

Log: https://gist.github.com/minimar/165171e164f9c329503cea43e5776228

**Comment by fcastilloec** [comment]
Thanks for reporting this, I'll take a look to see if I can reproduce it. I really appreciate that you included the logs! It's going to make it easier for me.

**Comment by fcastilloec** [comment]
Thanks again for the log, it made fixing this so much easier. I just pushed a fix for this and I'll be releasing a new version later today or probably over the weekend.
The problem only happens on songs that don't have an artist. Usually, all songs have an artist but there seems to be a bug with the module we use for parsing. If the artist's name contains a single quote `'`, it can't parse it. So this problem shouldn't happen to the great majority of songs/artists.
