### ISSUE TITLE
Tracklist Crash

### ISSUE THREAD

**Issue by SpencerTheGoalie** [headsetapp/headset-electron#503]
### Description

Whenever I have a playlist playing,  I click on one of the song badges and the whole app closes

### Expected behaviour

Should be able to pick songs from the tracklist without app crashing.

### Actual behaviour

Everytime I play one of my playlists, and try skipping to a certain song in the tracklist, I click the song and the app completely closes.

### Your Environment

- What OS are you using? Windows 10 Home
- What version of Headset? Core: v2.11.0, Wrapper: v4.1.1

### Screenshots

🖼

**Comment by fcastilloec** [comment]
I'm sorry but I can't reproduce this. Could you share a link to the YouTube playlist with the problem? or is it happening with every single playlist?
In addition, could you please share the log files? They should be under `{your-user}\AppData\Roaming\Headset\logs`, there should be a single file called `main.log`. This file gets rewritten every time you open the app (to save disk space). So make sure you send the file right after a crash, without opening Headset again.

**Comment by SpencerTheGoalie** [comment]
So I tested it again and it seems to be a rarer occurence, basically I start playing a song, scroll down to load more, then keep repeating until I get to the end of the playlist (so I can shuffle my whole playlist). After that, I'll click through songs in the tracklist, and it seems to crash on certain songs?? 
----
Anyways, here's my playlist link: (it's got over 2k songs so I might be overloading the app?)
(https://www.youtube.com/playlist?list=PLnKb1hGcVtj1Bms7ZpDegSzkF-lYIii8j)
----
And here's the main.log after the crash:
[main.log](https://github.com/headsetapp/headset-electron/files/9354619/main.log)

**Comment by fcastilloec** [comment]
Thanks for the log!!! It makes it so much easier to see what's going on.
I can see the problem is with the Discord integration, so as a temporary workaround, you can disable Discord and it shouldn't crash anymore.
I'll come up with a fix so this doesn't happen again 🤞🏼

**Comment by fcastilloec** [comment]
@SpencerTheGoalie I've released a new version that includes a workaround for this issue. Hopefully, you won't encounter any crashes related to Discord anymore
