### ISSUE TITLE
Add a reddit Radio

### ISSUE THREAD

**Issue by Joseph65** [headsetapp/headset-electron#52]
it would be nice if we could add a custom reddit radio, for example /r/kpop or /r/citypop/

**Comment by m1guelpf** [comment]
:+1: for this!

**Comment by danielravina** [comment]
👍 This will be a part of an all around search initiative that I'm working on. Basically, every page will have its own search bar (i.e search within your collections, likes, etc.) The radio will be a filter type that you could add subs that do not exist (and save them too)

**Comment by danielravina** [comment]
Feature added https://twitter.com/headsetapp/status/899512234178560000

**Comment by danielravina** [comment]
closed by mistake. @Joseph65 I'll let you close it off

next release for that page will be the ability to save / bookmark so you won't have to search everytime
