### ISSUE TITLE
installation in fedora

### ISSUE THREAD

**Issue by sunnlife** [headsetapp/headset-electron#55]
Hi, 
i followed your instructions to build and install Headset with electron packager but nothing happens in step 3 (Create your build).
Could you help me please ?
thanks in advance

Alex

**Comment by m1guelpf** [comment]
@sunnlife You can try to use Alien to convert the .deb release to a .rpm package yum can install...
[Reference](https://www.systutorials.com/qa/212/how-to-install-deb-packages-on-fedora).

**Comment by sunnlife** [comment]
Thanks for your answer.
I tried to convert but when i install the rpm package i have an error message: "Conflict with filesystem-3.2-40.fc26.x86_64 package" ...

**Comment by m1guelpf** [comment]
@sunnlife Then, I think we need a .rpm build, don't we @danielravina?

**Comment by sunnlife** [comment]
Agree ! ;-)

**Comment by fcastilloec** [comment]
I'm going to test a build script for rpm. I'll let you guys know how it goes

**Comment by fcastilloec** [comment]
@sunnlife can you please test this new `rpm` package? [Headset-1.6.0.amd64.rpm](https://drive.google.com/open?id=0B9DkUtc21XAAVTIzdEhfb0JJVVk)
Just in case the SHA256 checksum is: `ef01e123931d77d62452ebd4dbbb7931bf531613ce3ff20a4e3ae0b2689929c1`

Let me know if there are any errors. I tested it on a virtual machine running Fedora 26.  If everything is working as it should, I'll do a PR to add support for `rpm` packages.

**Comment by sunnlife** [comment]
Hi fcastilloec !

Thanks !! It works fine !!!

**Comment by sunnlife** [comment]
It works in F26

**Comment by danielravina** [comment]
Available in https://github.com/headsetapp/headset-electron/releases/tag/v1.6.0-linux
