### ISSUE TITLE
Flatpak org.freedesktop.Platform runtime branch 21.08 reached end-of-life

### ISSUE THREAD

**Issue by IzNoGud78** [headsetapp/headset-electron#588]
### Description

The Headset's flatpak version needs to be upgraded to a supported `org.freedesktop.Platform` runtime version because branch 21.08 is no longer receiving fixes and security updates (EoL).

### Expected behaviour

Even if Headset application continues to run smoothly, it should be upgraded to an updated runtime version so that updating flatpak packages will not display errors regarding the runtimes used by the Headset package.

### Actual behaviour

```
Info: runtime org.freedesktop.Platform branch 21.08 is end-of-life, with reason:
   org.freedesktop.Platform 21.08 is no longer receiving fixes and security updates. Please update to a supported runtime version.
Info: applications using this runtime:
   co.headsetapp.headset

Info: runtime org.freedesktop.Platform.VAAPI.Intel branch 21.08 is end-of-life, with reason:
   org.freedesktop.Platform 21.08 is no longer receiving fixes and security updates. Please update to a supported runtime version.
Info: applications using this extension:
   co.headsetapp.headset

Info: runtime org.freedesktop.Platform.GL.default branch 21.08 is end-of-life, with reason:
   org.freedesktop.Platform 21.08 is no longer receiving fixes and security updates. Please update to a supported runtime version.
Info: applications using this extension:
   co.headsetapp.headset

```

### Your Environment

- OS: Fedora 38
- Headset version: Core: v2.11.0, Wrapper: v4.2.1

**Comment by fcastilloec** [comment]
Thanks for letting me know. I've already committed a change to use the newer runtime. See https://github.com/flathub/co.headsetapp.headset/pull/7 
I don't know how long it'll take to be available on Flathub

**Comment by fcastilloec** [comment]
Thanks for letting me know. I've already committed a change to use the newer runtime. See https://github.com/flathub/co.headsetapp.headset/pull/7 
I don't know how long it'll take to be available on Flathub
