### ISSUE TITLE
The player stops if a video is unavailable.

### ISSUE THREAD

**Issue by sameer-pandit** [headsetapp/headset-electron#6]
When a youtube video is unavailable due to country restriction etc.. the app should skip it and move onto next. See below screenshot the player has just hanged.
![1](https://cloud.githubusercontent.com/assets/8393949/26069508/b4d1d928-39be-11e7-8bc6-d9585d8b6ede.png)

**Comment by danielravina** [comment]
Yeah, this is a known issue. Unfortunately, the embedded player doesn't throw any error or trigger any event when this happens. This needs a more sophisticated way to detect it. Thank you for reporting it. I'll keep the issue open until I get it fixed.

**Comment by danielravina** [comment]
The issue is fixed and is now live. care to try it out?
