### ISSUE TITLE
Play Similar Songs Feature Broken

### ISSUE THREAD

**Issue by Zapdorf** [headsetapp/headset-electron#616]
The "Play Similar Songs" feature stopped working for me. Clicking the menu option in the ellipsis next to a song/video does nothing. I get the same result no matter what song/video I try. The result is also the same across different contexts (i.e. likes section, playing from a playlist or collection, etc). I've tried reinstalling and I've tried using other devices (same version and OS) without success. 

I'm using version 4.2.1 on Windows 10

**Comment by fcastilloec** [comment]
Thanks for reporting this. I've been very busy, but we'll get to fixing this soon enough

**Comment by Zapdorf** [comment]
Awesome. Thank you!

**Comment by fcastilloec** [comment]
So, the reason why this is happening is that Google has removed support for this feature in their APIs. We won't be able to fix this at all, Google is not giving us a replacement way to fetch similar songs anymore.

I'm sorry about it. We might release a new version removing this menu completely, until then, we'll pin this issue, just in case people come across the same problem.
