### ISSUE TITLE
Support for arch Linux

### ISSUE THREAD

**Issue by tareqmahmud** [headsetapp/headset-electron#7]
It'll be great if someone makes aur package for this app.

Thanks.

**Comment by danielravina** [comment]
Hi! I updated the Readme with instructions on how to build for other environments. It's pretty easy so you can DIY. Let me know how it works for you.

**Comment by tareqmahmud** [comment]
It works great.
![headset](https://cloud.githubusercontent.com/assets/4035645/26090318/f36adee8-3a25-11e7-8fcb-38418dc6937f.png)

Thanks, man <3
