### ISSUE TITLE
Headset doesn't work on Lubuntu

### ISSUE THREAD

**Issue by fcastilloec** [headsetapp/headset-electron#72]
v1.6.0 is broken on Lubuntu because that OS is not based on Gnome.
The latest code on github does work and installs without a problem. The commit https://github.com/headsetapp/headset-electron/commit/b6b102d0a4f07b4212494f8d635abcedd40d1426 solved the problem by adding extra dependencies to the `.deb` package.

Users should install the package from the repositories which will fix the problem

**Comment by danielravina** [comment]
Fixed in https://github.com/headsetapp/headset-electron/releases/tag/v1.6.1
