### ISSUE TITLE
Save radio stations

### ISSUE THREAD

**Issue by danielravina** [headsetapp/headset-electron#77]
As a follow up to #52, the next step is to allow users to save their favourite stations and pin them to the top.

**Comment by cyra** [comment]
I double thumbs up this, was gonna open an issue for this. Would be really helpful if users could pin/save/favourite a youtube channel or a subreddit.

**Comment by danielravina** [comment]
A UX question: Would you rather see your saved subreddits on the radio tab or somewhere in your saved collections tab? I got this feature pretty much ready to go, just not sure yet where to place it exactly.

**Comment by m1guelpf** [comment]
@danielravina I'd expect them to be pinned to the top of the radio tab, in a section before the All Music one.

**Comment by danielravina** [comment]
The feature is ready! you'll see it the next time you open the app

Have fun
