### ISSUE TITLE
brew cask package

### ISSUE THREAD

**Issue by niftylettuce** [headsetapp/headset-electron#80]
can you please add this to brew?  `brew cask install headset` would be nice

**Comment by danielravina** [comment]
Believe it or not, someone already did it :) Just found out now when tried to submit! Thanks @victorpopkov! :)

**Comment by danielravina** [comment]
+ Added homebrew instructions to the readme

**Comment by m1guelpf** [comment]
@danielravina Is there any way to make sure the cask package is always updated?

**Comment by danielravina** [comment]
This could probably be done automatically with travis using https://github.com/caskroom/homebrew-cask/blob/master/CONTRIBUTING.md#updating-a-cask. I'll want to wait on this though as the mac build is not fully ready
