### ISSUE TITLE
Fix Travis before_deploy

### ISSUE THREAD

**Issue by fcastilloec** [headsetapp/headset-electron#81]
I notice that Travis is showing some errors when deploying and it's because the `before_deploy` should be only run when deploying to `gh-pages` and not to `releases`.
Right now, I'm not aware of this causing any problems, but it should be fixed anyways.
I will fix this issue. I'm just reporting it here so to keep track of it and not forget it.

**Comment by danielravina** [comment]
Fixed with #84
