### ISSUE TITLE
JavaScript error while using media shortcut keys (next track / previous track) on a windows machine. 

### ISSUE THREAD

**Issue by rajat-np** [headsetapp/headset-electron#82]
When headset is running , the keys work with itself, but when I quit the app , headset closes but I cannot use the media shortcut keys from my keyboard, it gives me an js error.

**Comment by danielravina** [comment]
Are you using the latest version? 1.6.1

**Comment by rajat-np** [comment]
No i am using version 1.5.4.

**Comment by rajat-np** [comment]
The issue is solved in the new version. Great!!
