### ISSUE TITLE
Media shortcut keys on keyboard not working with ubuntu 14.04 LTS. 

### ISSUE THREAD

**Issue by rajat-np** [headsetapp/headset-electron#83]

**Comment by fcastilloec** [comment]
@rajat-np which version of Headset are you using? and how did you installed the app? (repository, deb, source, etc)

**Comment by rajat-np** [comment]
I installed using deb file. this is the file. "Headset_1.5.4_amd64.deb"

**Comment by danielravina** [comment]
Hi! Please try to use the latest version: https://github.com/headsetapp/headset-electron/releases/download/v1.6.1/headset_1.6.1_amd64.deb

**Comment by rajat-np** [comment]
Yes sir , i installed the latest version and the issue is fixed , thanks.
