### ISSUE TITLE
Links not copied to clipboard.

### ISSUE THREAD

**Issue by Foxylizer** [headsetapp/headset-electron#92]
### Description

When trying to share a link, while Headset claims the link is copied, when I go to paste it, it actually isn't.

### Expected behaviour

The link is copied, I can paste it.

### Actual behaviour

The link can't paste.

### Environment

Windows 10 -Version 1709
Headset -Version 1.3.6

### Screenshots

![image](https://user-images.githubusercontent.com/29559592/33798075-f90072fa-dcd7-11e7-9b9e-66b5829d625d.png)

![image](https://user-images.githubusercontent.com/29559592/33798052-b15418c6-dcd7-11e7-9135-598d045ee9b1.png)

![image](https://user-images.githubusercontent.com/29559592/33798062-c4cdf8b8-dcd7-11e7-818a-9b9680a5dffd.png)

**Comment by fcastilloec** [comment]
I remember that this use to work last week or two weeks ago. Nonetheless, right now it doesn't work.
Using the latest release available: **Linux** Core: 1.3.6, Wrapper: v1.6.2, Windows: Core: 1.3.6, Wrapper: v1.6.1; I can duplicate this bug on both 32 and 64bit Debian and Redhat distros and all Windows version (7, 8.1, 10)

**Comment by danielravina** [comment]
Bug fixed (Core: 1.3.7). Sorry about that!

**Comment by fcastilloec** [comment]
I can confirm that Core: 1.3.7 fixes the issue on all OSs

**Comment by danielravina** [comment]
Thanks @fcastilloec! closing now.
