### ISSUE TITLE
ability to always access the current queue

### ISSUE THREAD

**Issue by sibeliusg** [headsetapp/headset-electron#94]
Sometimes it happens (in a new search f.e.), that the visibility of the current queue disappears. A simple icon to access the current queue could fix this.

Using Headset 1.6.1 on Windows 10 x64

**Comment by danielravina** [comment]
Hi! What do you mean disappears? Can you send a screenshot or steps to reproduce, that will be helpful. Thanks a lot!

**Comment by fcastilloec** [comment]
I'm closing this issue as it's over two months and we never heard back from the original author
