### ISSUE TITLE
Add media key compatibility

### ISSUE THREAD

**Issue by knw257** [headsetapp/headset-electron#96]
The ability to control playback (play, pause, next, last) from keyboard media keys would be extremely useful.

**Comment by m1guelpf** [comment]
Duplicate https://github.com/headsetapp/headset-electron/issues/83 https://github.com/headsetapp/headset-electron/issues/82 https://github.com/headsetapp/headset-electron/issues/70 https://github.com/headsetapp/headset-electron/issues/5

**Comment by fcastilloec** [comment]
@knw257 There's a template for filling issues so it's easier for us to help. It's helpful to know what OS are you using, and what version of Headset (both core and wrapper versions)
I'm going to go out on a limb and say that you're not using the latest version of Headset, v1.6.1 (v1.6.2 hasn't been published yet).
If you're using Linux, please use the repositories to install, so you'll have the latest version always.

**Comment by knw257** [comment]
Ahh, my apologies for the substandard submission.

I'm currently running Windows 7, and I couldn't find any documentation indicating that the media keys were supposed to work. I also somehow missed the issues this was marked as a dup for. Currently, I'm running Core 1.3.7, Wrapper 1.6.1. 

Currently, none of the basic media keys (e.g. Play/Pause, Backward or Forward) work with Headset. I've verified they work in other applications (e.g. WinAmp, Google Play Music Desktop Player, VLC).

**Comment by fcastilloec** [comment]
I only have a Windows 10 machine where this is not an issue. My Windows 7 and 8.1 are virtual machines so I can't test media keys there. I'm trying to find a keyboard mapper so I can test it on Windows 7.
@m1guelpf do you have windows 7? so you can replicate this?

**Comment by m1guelpf** [comment]
@fcastilloec Ubuntu only, sorry. In totally unrelated news, wine and playonlinux seem to work :smile:.

**Comment by fcastilloec** [comment]
@m1guelpf wow! I never thought of using wine with it. I use wine and mono to compile the installers but not run them.
@knw257 I was able to test the media keys with Windows 7 and 8.1 and they are working properly. On Windows, if an app has already got a hold of the keys, then a new one can't use them. So, I recommend you close all media apps that can interact with the media keys before launching Headset.
I'm going to mark this as close as I can't reproduce it.
